"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");
const vm = require("node:vm");
const { execFileSync } = require("node:child_process");

function run(command, args) {
  return execFileSync(command, args, { encoding: "utf8" }).trim();
}

function verifyMainSourceSyntax() {
  execFileSync(process.execPath, ["--check", path.resolve(__dirname, "..", "src", "main.js")], {
    stdio: "pipe",
    encoding: "utf8",
  });
}

function verifyMainSourceBusinessGuards() {
  const mainSourcePath = path.resolve(__dirname, "..", "src", "main.js");
  const mainSource = fs.readFileSync(mainSourcePath, "utf8");

  assert.match(
    mainSource,
    /\["confirmed", "accepted"\]\.includes\(switchResult\.verificationStatus\)[\s\S]*detachWindowsDisplayForMonitor/u
  );
  assert.match(mainSource, /function classifyWindowsSwitchVerification/u);
  assert.match(mainSource, /\["confirmed", "accepted"\]\.includes\(result\?\.verificationStatus\)/u);
  assert.match(mainSource, /MAC_DISPLAY_METADATA_CACHE_TTL_MS = 5000/u);
  assert.match(mainSource, /screen\.getPrimaryDisplay\(\)\?\.id/u);
  assert.match(mainSource, /DISPLAY_NAME_FALLBACK_ALLOWED: displaySummary\.displayNameIsUnique \? "1" : "0"/u);
  assert.match(mainSource, /const resolvedMonitorId = normalizeText\(matchingMonitorConfig\?\.id\) \|\| displaySummary\.id;/u);
  assert.match(mainSource, /singleMacSoftMatchAllowed/u);
  assert.match(mainSource, /function shouldAllowSingleMacSoftDisplayMatch/u);
  assert.match(mainSource, /function isSingleMacSoftDisplayMatch/u);
  assert.match(mainSource, /function buildMacSoftDisplayKey/u);
  assert.match(mainSource, /function withDisplayNameUniqueness/u);
  assert.match(mainSource, /async function attemptPendingWindowsRestores\(\{\s*monitorId: targetMonitorId = null,\s*forceTopologyRefresh = false,/u);
  assert.match(mainSource, /pendingMonitorConfigs\.length === 0/u);
  assert.match(mainSource, /isWindowsInputValueForTarget\(currentInput\.value, localTarget, monitorConfig\)/u);
  assert.doesNotMatch(mainSource, /allowAttachDetached/u);
  assert.match(mainSource, /const windowsTakeoverInProgressMonitorIds = new Set\(\)/u);
  assert.match(mainSource, /const windowsTakeoverProtectedUntilByMonitorId = new Map\(\)/u);
  assert.match(mainSource, /WINDOWS_TAKEOVER_SETTLE_MS = 45000/u);
  assert.match(mainSource, /async function attemptWindowsDuplicateForeignDisplayDetaches/u);
  assert.match(mainSource, /function getWindowsDuplicateDisplayIdentityKey/u);
  assert.match(mainSource, /function isWindowsInputValueForTarget/u);
  assert.match(mainSource, /function isWindowsInputValueForConfiguredExternalHandoffTarget/u);
  assert.match(mainSource, /function isExternalWindowsHandoffTargetId/u);
  assert.doesNotMatch(mainSource, /differs from configured local input/u);
  assert.match(mainSource, /isWindowsTakeoverInProgress\(monitorConfig\)/u);
  assert.match(mainSource, /function isWindowsTakeoverInProgress/u);
  assert.match(mainSource, /function markWindowsTakeoverProtection/u);
  assert.match(mainSource, /function queueMonitorOperation/u);
  assert.match(mainSource, /takeoverWindowsDetachedMonitorUnlocked/u);
  assert.match(mainSource, /function killProcessTree/u);
  assert.match(mainSource, /taskkill\.exe/u);
  assert.match(mainSource, /稳定保留这块屏/u);
  assert.match(mainSource, /stableMs = 0/u);
  assert.match(mainSource, /WINDOWS_TOPOLOGY_COMMAND_TIMEOUT_MS/u);
  assert.match(mainSource, /WINDOWS_DDC_PROBE_TIMEOUT_MS/u);
  assert.match(mainSource, /!shouldUseWindowsDisplayHandoffForMonitor\(monitorConfig, attachedDisplays\.length\)/u);
  assert.match(mainSource, /pendingAwayAndUnverified/u);
  assert.match(mainSource, /async function takeoverWindowsDetachedMonitor/u);
  assert.match(mainSource, /function getWindowsDetachedTakeoverContexts/u);
  assert.match(mainSource, /function getWindowsHeuristicDetachedTakeoverDisplays/u);
  assert.match(mainSource, /function pruneRedundantWindowsHeuristicTakeoverConfigs/u);
  assert.match(mainSource, /const hasExplicitDetachedConfig = storedMonitorConfigs\.some/u);
  assert.match(mainSource, /pruneRedundantWindowsHeuristicTakeoverConfigs\(\s*connectedMonitorIds,\s*resolvedTopologyDisplays/u);
  assert.match(mainSource, /function isWindowsAutoGeneratedTakeoverConfig/u);
  assert.match(mainSource, /function renderWindowsTakeoverSection/u);
  assert.match(mainSource, /function getUsageIntroText/u);
  assert.match(mainSource, /function renderUsageGuide/u);
  assert.match(mainSource, /function renderDailyVisibleMonitorActions/u);
  assert.match(mainSource, /place-items: start center;/u);
  assert.match(mainSource, /width: min\(calc\(100vw - 32px\), 920px\);/u);
  assert.match(mainSource, /width: calc\(100vw - 24px\);/u);
  assert.match(mainSource, /main \{[\s\S]{0,160}min-width: 0;[\s\S]{0,80}box-sizing: border-box;/u);
  assert.match(mainSource, /overflow-wrap: anywhere;/u);
  assert.match(mainSource, /"PingFang SC", "Microsoft YaHei", "Noto Sans SC"/u);
  assert.match(mainSource, /function getPreferredPeerTargetId/u);
  assert.match(mainSource, /function getConfiguredPeerInterfaceId/u);
  assert.match(mainSource, /peerInterfaceId: parseTargetId/u);
  assert.match(mainSource, /日常交给对方接口/u);
  assert.doesNotMatch(mainSource, /configuredPeerTargetId/u);
  assert.match(mainSource, /日常逻辑/u);
  assert.match(mainSource, /灰色第二屏/u);
  assert.match(mainSource, /高级：单独切输入源 \/ 校准 DDC 值/u);
  assert.match(mainSource, /交给\$\{escapeHtml\(getPeerMachineLabel\(peerTargetId, monitorContext\.monitor\)\)\}/u);
  assert.match(mainSource, /deviceLabel: normalizeText/u);
  assert.match(mainSource, /连接设备名（可选）/u);
  assert.match(mainSource, /当前没有可接回共享屏/u);
  assert.match(mainSource, /待接回屏幕/u);
  assert.match(mainSource, /自动：交给对方时移出桌面，接回时恢复/u);
  assert.doesNotMatch(mainSource, /回来后自动接回/u);
  assert.doesNotMatch(mainSource, /Mac mini \/ 对方机器/u);
  assert.doesNotMatch(mainSource, /Windows 主动接管失败/u);
  assert.match(mainSource, /\/windows\/takeover\//u);
  assert.match(mainSource, /await attachWindowsDisplayForMonitor\(/u);
  assert.match(mainSource, /async function switchWindowsDisplayForMonitorConfig/u);
  assert.match(mainSource, /await switchWindowsDisplayForMonitorConfig\(monitorConfig, localTarget\)/u);
  assert.match(mainSource, /function formatWindowsTakeoverError/u);
  assert.match(mainSource, /不向 Windows 暴露控制句柄/u);
  assert.match(mainSource, /"-GdiDeviceName",\s*deviceName/u);
  assert.match(mainSource, /normalizeText\(monitorConfig\?\.match\?\.gdiDeviceName\)/u);
  assert.match(mainSource, /const externalDisplays = orderedDisplays\.filter\(\(display\) => !display\.internal\);/u);
  assert.match(
    mainSource,
    /\.filter\(\(\{ electronDisplay \}\) => Boolean\(electronDisplay\) && !electronDisplay\.internal\);/u
  );
  assert.match(mainSource, /startDisplayChangeWatcher\(\);/u);
  assert.match(mainSource, /function scheduleLocalDisplayTopologyChange/u);
  assert.match(mainSource, /DISPLAY_CHANGE_DEBOUNCE_MS = 750/u);
  assert.match(mainSource, /WINDOWS_RESTORE_CHECK_INTERVAL_MS = 15000/u);
  assert.match(mainSource, /screen\.on\("display-added", handleDisplayChange\);/u);
  assert.match(mainSource, /screen\.on\("display-metrics-changed", handleDisplayChange\);/u);
  assert.match(mainSource, /forceMacDisplayMetadataRefresh/u);
  assert.match(mainSource, /system_profiler", \["SPDisplaysDataType", "-json"\]/u);
  assert.match(mainSource, /monitorEntry\?\.\["_spdisplays_display-vendor-id"\]/u);
  assert.match(mainSource, /monitorEntry\?\.\["_spdisplays_display-product-id"\]/u);
  assert.match(mainSource, /monitorEntry\?\.\["_spdisplays_display-serial-number"\]/u);
  assert.doesNotMatch(mainSource, /monitorEntry\?\._spdisplays_display-vendor-id/u);
  assert.doesNotMatch(mainSource, /monitorEntry\?\._spdisplays_display-product-id/u);
  assert.doesNotMatch(mainSource, /monitorEntry\?\._spdisplays_display-serial-number/u);
  assert.match(mainSource, /function isMacProfilerDisplayResolutionMatch/u);
  assert.match(mainSource, /function doesWindowsElectronDisplayExactlyMatchTopology/u);
  assert.match(mainSource, /function doesWindowsElectronDisplaySizeMatchTopology/u);
  assert.match(mainSource, /function getStateBackupPath/u);
  assert.match(mainSource, /function normalizeWindowsRestoreLayout/u);
  assert.match(mainSource, /topologyDisplay\.primary/u);
  assert.match(
    mainSource,
    /await detachWindowsDisplayForMonitor\(\s*monitorConfig,\s*attachedDisplayCountBeforeSwitch,\s*buildWindowsRestoreLayout\(topologyDisplay\)\s*\)/u
  );
  assert.doesNotMatch(mainSource, /remainingMatches\.length === remainingDisplays\.length/u);
  assert.doesNotMatch(mainSource, /remainingMatches\[index\]\.electronDisplay = remainingDisplays\[index\]/u);
  assert.doesNotMatch(mainSource, /candidate\.width === display\?\.bounds\?\.width/u);
  assert.doesNotMatch(mainSource, /Skipping Windows desktop detach for primary display/u);
  assert.match(mainSource, /promoteWindowsPrimaryAwayBeforeSwitch/u);
  assert.match(mainSource, /-PromotePrimaryAwayFromMonitor/u);
  assert.match(mainSource, /getWindowsDdcProbeResultsByDeviceName/u);
  assert.match(mainSource, /attachMacDdcProbeResults/u);
  assert.match(mainSource, /function createDdcProbeSummary/u);
  assert.match(mainSource, /function isMonitorDirectSwitchEnabled/u);
  assert.match(mainSource, /ddcProbe: createDdcProbeSummary/u);
  assert.match(mainSource, /runtimeStatus\.ddcAvailable === false/u);
  assert.match(mainSource, /statusText = "当前不可控"/u);
  assert.doesNotMatch(mainSource, /return getMacDdcCapableDisplaySummaries\(externalDisplaySummaries\)/u);
  assert.match(mainSource, /statusText = "当前输入未知"/u);
  assert.doesNotMatch(mainSource, /statusText = "读取失败"/u);
  assert.doesNotMatch(mainSource, /没有真正切到/u);
  assert.match(mainSource, /timeout: HELPER_COMMAND_TIMEOUT_MS/u);
  assert.match(mainSource, /CURRENT_INPUT_COMMAND_TIMEOUT_MS = 5000/u);
  assert.match(mainSource, /timeout: CURRENT_INPUT_COMMAND_TIMEOUT_MS/u);
  assert.match(mainSource, /SYSTEM_PROFILER_COMMAND_TIMEOUT_MS = 45000/u);
  assert.match(mainSource, /LOCAL_REQUEST_BODY_LIMIT_BYTES = 64 \* 1024/u);
  assert.match(mainSource, /switchOperationQueue = Promise\.resolve\(\)/u);
  assert.match(mainSource, /switchInFlightByMonitorId/u);
  assert.match(mainSource, /async function switchMonitorUnlocked/u);
  assert.match(mainSource, /switchOperationQueue = switchTask\.catch\(\(\) => \{\}\)/u);
  assert.match(mainSource, /function shouldPreserveDisconnectedMonitorConfig/u);
  assert.match(mainSource, /function getStoredMonitorConfigMatchScore/u);
  assert.match(mainSource, /windowsDisplayDeviceId/u);
  assert.match(mainSource, /win-device:/u);
  assert.match(mainSource, /storedDisplayDeviceId === topologyDisplayDeviceId/u);
  assert.match(mainSource, /preservedWindowsDeviceNames/u);
  assert.match(mainSource, /isWindowsPhysicalDetachedDisplayCandidate\(topologyDisplay\)/u);
  assert.match(mainSource, /process\.platform === "darwin"[\s\S]{0,120}hasMacPersistableMonitorIdentity/u);
  assert.match(mainSource, /function findStoredMonitorConfigForDisplay/u);
  assert.match(mainSource, /customizedMacSoftMatches\.length === 1/u);
  assert.match(mainSource, /function isUserCustomizedMonitorConfig/u);
  assert.match(mainSource, /function isUsableMacHardwareId/u);
  assert.match(mainSource, /function getMacPersistableMonitorIdentityKey/u);
  assert.match(mainSource, /function hasMacPersistableMonitorIdentity/u);
  assert.match(mainSource, /function isGenericMacDisplayName/u);
  assert.match(mainSource, /preservedMacIdentityKeys/u);
  assert.doesNotMatch(mainSource, /buildMacSoftDisplayKey\(monitorConfig\) \|\|\s*normalizeText\(monitorConfig\.displayKey\)/u);
  assert.match(mainSource, /function pruneStateForKnownMonitorIds/u);
  assert.match(mainSource, /function normalizePersistedSwitchOutcome/u);
  assert.match(mainSource, /function shouldClearPersistedSwitchOutcome/u);
  assert.match(mainSource, /lastSwitchOutcome: normalizePersistedSwitchOutcome/u);
  assert.match(mainSource, /outcomeMessage: successMessages\.outcomeMessage/u);
  assert.match(mainSource, /createHttpError\(413, "请求内容过大。"\)/u);
  assert.match(mainSource, /function getHealthConnectedMonitorSummaries/u);
  assert.match(mainSource, /connectedMonitors: getHealthConnectedMonitorSummaries\(\)/u);
  assert.doesNotMatch(
    mainSource,
    /requestUrl\.pathname === "\/health"[\s\S]{0,300}getConnectedMonitorContexts/u
  );
  assert.match(mainSource, /function parseLocalRequestUrl\(request\)/u);
  assert.match(mainSource, /`http:\/\/\$\{LOOPBACK_HOST\}:\$\{getListeningPort\(\)\}`/u);
  assert.match(mainSource, /function decodePathSegment\(value\)/u);
  assert.match(mainSource, /createHttpError\(400, "请求路径编码无效。"\)/u);
  assert.doesNotMatch(mainSource, /request\.headers\.host/u);
  assert.match(mainSource, /function shouldLogControlRequestError\(error\)/u);
  assert.match(mainSource, /if \(shouldLogControlRequestError\(error\)\) \{\s*appendDiagnosticLog\("Control request failed", error\);/u);
  assert.match(mainSource, /async function mapSequential\(items, mapper\)/u);
  assert.match(mainSource, /const probeResults = await mapSequential\(/u);
  assert.match(mainSource, /function shouldUseWindowsPowerShellTemp\(file\)/u);
  assert.match(mainSource, /function getWindowsPowerShellEnv\(\)/u);
  assert.match(mainSource, /function getWindowsHelperTempPath\(\)/u);
  assert.match(mainSource, /function getWindowsPowerShellScriptArgs\(/u);
  assert.match(mainSource, /function resolveHelperCommandInvocation\(/u);
  assert.match(mainSource, /function getWindowsPowerShellExecutablePath\(/u);
  assert.match(mainSource, /"-WindowStyle",\s*"Hidden"/u);
  assert.match(mainSource, /getBundledResourcePath\("windows", "hidden-process\.exe"\)/u);
  assert.match(
    mainSource,
    /args: \[getWindowsPowerShellExecutablePath\(\), \.\.\.normalizedArgs\]/u
  );
  assert.doesNotMatch(mainSource, /runCommand\("powershell\.exe",\s*\[/u);
  assert.doesNotMatch(mainSource, /conhost\.exe|--headless/u);
  assert.match(mainSource, /shell: false,\s*windowsHide: true/u);
  assert.match(mainSource, /execFile\(invocation\.file, invocation\.args/u);
  assert.match(mainSource, /WINDOWS_TOPOLOGY_FAILURE_BACKOFF_MAX_MS = 60000/u);
  assert.match(mainSource, /WINDOWS_TOPOLOGY_CACHE_TTL_MS = 30 \* 1000/u);
  assert.match(mainSource, /WINDOWS_TOPOLOGY_LOG_INTERVAL_MS = 60 \* 60 \* 1000/u);
  assert.match(mainSource, /function getCachedWindowsTopologyDisplays/u);
  assert.match(mainSource, /allowCachedOnFailure: false/u);
  assert.match(mainSource, /throwOnFailure: true/u);
  assert.match(mainSource, /EXPLORER_SIGNATURE_TIMEOUT_MS = 3000/u);
  assert.match(mainSource, /EXPLORER_SIGNATURE_LOG_INTERVAL_MS = 60 \* 60 \* 1000/u);
  assert.match(mainSource, /trayHealthCheckInFlight/u);
  assert.match(mainSource, /runCommand\(\s*"tasklist\.exe"/u);
  assert.match(mainSource, /function parseExplorerSignature/u);
  assert.doesNotMatch(mainSource, /Get-Process explorer/u);
  assert.match(mainSource, /appendDiagnosticLogRateLimited\(\s*"windows-topology-read"/u);
  assert.match(mainSource, /function trimDiagnosticLogIfNeeded/u);
  assert.match(mainSource, /function createDiagnosticLogEntry/u);
  assert.match(mainSource, /function truncateDiagnosticLogText/u);
  assert.match(
    mainSource,
    /app\.whenReady\(\)\.then[\s\S]{0,240}trimDiagnosticLogIfNeeded\(\);/u
  );
  assert.match(mainSource, /DIAGNOSTIC_LOG_MAX_BYTES = 64 \* 1024/u);
  assert.match(mainSource, /DIAGNOSTIC_LOG_TAIL_BYTES = 24 \* 1024/u);
  assert.match(mainSource, /DIAGNOSTIC_LOG_ENTRY_MAX_BYTES = 8 \* 1024/u);
  assert.doesNotMatch(mainSource, /appendDiagnosticLog\(`Rebuilding tray/u);
  assert.match(mainSource, /TEMP: tempPath/u);
  assert.match(mainSource, /TMP: tempPath/u);
  assert.match(mainSource, /<link rel="icon" href="data:,">/u);
  assert.doesNotMatch(mainSource, /request\.destroy\(\)/u);
  assert.match(mainSource, /function hasMacPhysicalIdentity/u);
  assert.match(mainSource, /function hasMacSafeDdcTargetIdentity/u);
  assert.match(mainSource, /targetable-unconfirmed/u);
  assert.match(mainSource, /confirmed: ok && status === "ok"/u);
  assert.match(mainSource, /if \(forceRefresh\) \{\s*macDisplayMetadataCache = \{\s*fetchedAt: 0,\s*displays: \[\],\s*\};\s*return \[\];\s*\}/u);
  assert.doesNotMatch(mainSource, /:\s*displaySummary\.electronDisplayId/u);
  assert.match(mainSource, /function runSwitchCandidateSequence/u);
  assert.match(mainSource, /getExpectedProbeInputValues\(target\.inputValue, monitorContext\.monitor\)/u);
  assert.match(mainSource, /function parseStrictInteger/u);
}

function extractFunction(source, name) {
  const start = source.indexOf(`function ${name}(`);
  assert.notEqual(start, -1, `Missing function ${name}`);
  const declarationEnd = source.indexOf(") {", start);
  const bodyStart = declarationEnd >= 0
    ? source.indexOf("{", declarationEnd)
    : source.indexOf("{", start);
  let depth = 0;

  for (let index = bodyStart; index < source.length; index += 1) {
    const char = source[index];
    if (char === "{") {
      depth += 1;
    } else if (char === "}") {
      depth -= 1;
      if (depth === 0) {
        return source.slice(start, index + 1);
      }
    }
  }

  throw new Error(`Could not extract function ${name}`);
}

function verifyMacMonitorConfigSyncBehavior() {
  const mainSourcePath = path.resolve(__dirname, "..", "src", "main.js");
  const mainSource = fs.readFileSync(mainSourcePath, "utf8");
  const functionNames = [
    "normalizeText",
    "parseTargetId",
    "getTarget",
    "getLocalInterfaceId",
    "getConfiguredPeerInterfaceId",
    "isUserCustomizedMonitorConfig",
    "hasMacPhysicalIdentity",
    "isUsableMacHardwareId",
    "buildMacHardwareDisplayKey",
    "buildMacSoftDisplayKey",
    "isSingleMacSoftDisplayMatch",
    "getMacPersistableMonitorIdentityKey",
    "isGenericMacDisplayName",
    "findStoredMonitorConfigForDisplay",
  ];
  const helperSource = functionNames.map((name) => extractFunction(mainSource, name)).join("\n");
  const script = `
    const TARGET_SLOTS = [
      { id: "dp1", title: "DP1", defaultInputValue: 15 },
      { id: "dp2", title: "DP2", defaultInputValue: 16 },
      { id: "hdmi1", title: "HDMI1", defaultInputValue: 17 },
      { id: "hdmi2", title: "HDMI2", defaultInputValue: 18 },
    ];
    const TARGET_SLOT_MAP = new Map(TARGET_SLOTS.map((slot) => [slot.id, slot]));
    const TARGET_IDS = TARGET_SLOTS.map((slot) => slot.id);
    ${helperSource}
    const displaySummary = {
      displayKey: "mac-system:2",
      detectedName: "H24E7",
      macVendorId: "4d67",
      macProductId: "2431",
      macSerialNumber: "1",
      macSystemDisplayId: 2,
      electronDisplayId: 2,
    };
    const staleDefault = {
      id: "monitor-new",
      displayKey: "mac-system:2",
      displayName: "H24E7",
      localInterfaceId: "dp1",
      peerInterfaceId: "",
      interfaces: {},
      match: { macVendorId: "4d67", macProductId: "2431", macSerialNumber: "1" },
    };
    const calibrated = {
      id: "monitor-old",
      displayKey: "mac-system:1",
      displayName: "H24E7",
      localInterfaceId: "hdmi1",
      peerInterfaceId: "dp2",
      interfaces: {},
      match: { macVendorId: "4d67", macProductId: "2431", macSerialNumber: "1" },
    };
    const blankShell = {
      id: "monitor-blank",
      displayKey: "mac:5",
      displayName: "",
      localInterfaceId: "dp1",
      peerInterfaceId: "",
      interfaces: {},
      match: {},
    };
    const virtualShell = {
      id: "monitor-virtual",
      displayKey: "mac-system:7",
      displayName: "spdisplays_display",
      localInterfaceId: "dp1",
      peerInterfaceId: "",
      interfaces: {},
      match: { macVendorId: "756e6b6e", macProductId: "76697274" },
    };
    globalThis.result = {
      matchId: findStoredMonitorConfigForDisplay(
        displaySummary,
        [staleDefault, calibrated, blankShell, virtualShell],
        new Set(),
        true
      ).id,
      calibratedIdentity: getMacPersistableMonitorIdentityKey(calibrated),
      blankIdentity: getMacPersistableMonitorIdentityKey(blankShell),
      virtualIdentity: getMacPersistableMonitorIdentityKey(virtualShell),
      virtualPhysical: hasMacPhysicalIdentity({
        macVendorId: "756e6b6e",
        macProductId: "76697274",
      }),
    };
  `;
  const context = { process: { platform: "darwin" } };
  vm.runInNewContext(script, context);
  assert.equal(context.result.matchId, "monitor-old");
  assert.match(context.result.calibratedIdentity, /^mac-soft:4d67:2431:h24e7$/u);
  assert.equal(context.result.blankIdentity, "");
  assert.equal(context.result.virtualIdentity, "");
  assert.equal(context.result.virtualPhysical, false);
}

function verifyStrictIntegerParsing() {
  const mainSourcePath = path.resolve(__dirname, "..", "src", "main.js");
  const mainSource = fs.readFileSync(mainSourcePath, "utf8");
  const functionNames = [
    "normalizeText",
    "parseStrictInteger",
    "normalizePositiveInteger",
    "normalizeDisplayIdentifier",
    "parseInputValue",
  ];
  const helperSource = functionNames.map((name) => extractFunction(mainSource, name)).join("\n");
  const script = `
    ${helperSource}
    globalThis.result = {
      validInput: parseInputValue("17"),
      paddedInput: parseInputValue(" 017 "),
      decimalInput: parseInputValue("17.5"),
      suffixInput: parseInputValue("17abc"),
      negativeInput: parseInputValue("-1"),
      blankInput: parseInputValue(""),
      fallbackValid: normalizePositiveInteger("42", 7),
      fallbackInvalid: normalizePositiveInteger("42px", 7),
      displayZero: normalizeDisplayIdentifier("0"),
      displayInvalid: normalizeDisplayIdentifier("1x"),
    };
  `;
  const context = {};
  vm.runInNewContext(script, context);
  assert.equal(context.result.validInput, 17);
  assert.equal(context.result.paddedInput, 17);
  assert.equal(Number.isNaN(context.result.decimalInput), true);
  assert.equal(Number.isNaN(context.result.suffixInput), true);
  assert.equal(Number.isNaN(context.result.negativeInput), true);
  assert.equal(Number.isNaN(context.result.blankInput), true);
  assert.equal(context.result.fallbackValid, 42);
  assert.equal(context.result.fallbackInvalid, 7);
  assert.equal(context.result.displayZero, 0);
  assert.equal(context.result.displayInvalid, null);
}

function verifyMonitorConfigFormRejectsInvalidInputValues() {
  const mainSourcePath = path.resolve(__dirname, "..", "src", "main.js");
  const mainSource = fs.readFileSync(mainSourcePath, "utf8");
  const functionNames = [
    "normalizeText",
    "parseStrictInteger",
    "normalizePositiveInteger",
    "parseInputValue",
    "parseCompatibilityMode",
    "parseWindowsDisplayHandoffMode",
    "parseTargetId",
    "cloneInterfacesConfig",
    "createDefaultInterfacesConfig",
    "createDefaultMonitorConfig",
    "normalizeMonitorConfig",
    "getTargetSlotName",
    "getLocalInterfaceId",
    "getMonitorConfigValidationErrors",
    "buildMonitorConfigFromForm",
  ];
  const helperSource = functionNames.map((name) => extractFunction(mainSource, name)).join("\n");
  const script = `
    const TARGET_SLOTS = [
      { id: "dp1", title: "DP1", defaultInputValue: 15 },
      { id: "dp2", title: "DP2", defaultInputValue: 16 },
      { id: "hdmi1", title: "HDMI1", defaultInputValue: 17 },
      { id: "hdmi2", title: "HDMI2", defaultInputValue: 18 },
    ];
    const TARGET_SLOT_MAP = new Map(TARGET_SLOTS.map((slot) => [slot.id, slot]));
    const TARGET_IDS = TARGET_SLOTS.map((slot) => slot.id);
    ${helperSource}
    const existingMonitorConfig = {
      id: "monitor-test",
      displayKey: "mac-system:2",
      displayName: "H24E7",
      localInterfaceId: "hdmi1",
      peerInterfaceId: "dp2",
      compatibilityMode: "auto",
      windowsDisplayHandoffMode: "auto",
      interfaces: {
        dp1: { inputValue: 99, deviceLabel: "" },
        dp2: { inputValue: 16, deviceLabel: "" },
        hdmi1: { inputValue: 17, deviceLabel: "" },
        hdmi2: { inputValue: 18, deviceLabel: "" },
      },
      match: {},
    };
    const valid = buildMonitorConfigFromForm(new URLSearchParams(
      "localInterfaceId=hdmi1&peerInterfaceId=dp2&compatibilityMode=auto&windowsDisplayHandoffMode=auto&dp1InputValue=42&dp1DeviceLabel=&dp2InputValue=16&dp2DeviceLabel=&hdmi1InputValue=17&hdmi1DeviceLabel=&hdmi2InputValue=18&hdmi2DeviceLabel="
    ), existingMonitorConfig);
    const suffix = buildMonitorConfigFromForm(new URLSearchParams(
      "localInterfaceId=hdmi1&peerInterfaceId=dp2&compatibilityMode=auto&windowsDisplayHandoffMode=auto&dp1InputValue=17abc&dp1DeviceLabel=&dp2InputValue=16&dp2DeviceLabel=&hdmi1InputValue=17&hdmi1DeviceLabel=&hdmi2InputValue=18&hdmi2DeviceLabel="
    ), existingMonitorConfig);
    const outOfRange = buildMonitorConfigFromForm(new URLSearchParams(
      "localInterfaceId=hdmi1&peerInterfaceId=dp2&compatibilityMode=auto&windowsDisplayHandoffMode=auto&dp1InputValue=0&dp1DeviceLabel=&dp2InputValue=16&dp2DeviceLabel=&hdmi1InputValue=17&hdmi1DeviceLabel=&hdmi2InputValue=18&hdmi2DeviceLabel="
    ), existingMonitorConfig);
    globalThis.result = {
      validErrors: valid.errors,
      validDp1: valid.monitorConfig.interfaces.dp1.inputValue,
      suffixErrors: suffix.errors,
      outOfRangeErrors: outOfRange.errors,
    };
  `;
  const context = { URLSearchParams };
  vm.runInNewContext(script, context);
  assert.deepEqual(Array.from(context.result.validErrors), []);
  assert.equal(context.result.validDp1, 42);
  assert.deepEqual(Array.from(context.result.suffixErrors), ["DP1 的输入值必须是 1 到 255 的整数。"]);
  assert.deepEqual(Array.from(context.result.outOfRangeErrors), ["DP1 的输入值必须是 1 到 255 的整数。"]);
}

function verifyWindowsDetachedVirtualDisplaysRejected() {
  const mainSourcePath = path.resolve(__dirname, "..", "src", "main.js");
  const mainSource = fs.readFileSync(mainSourcePath, "utf8");
  const helperSource = [
    "normalizeText",
    "getWindowsDisplayDeviceNumber",
    "isWindowsPhysicalDetachedDisplayCandidate",
  ].map((name) => extractFunction(mainSource, name)).join("\n");
  const script = `
    ${helperSource}
    const physicalDeviceName = String.raw\`\\\\.\\DISPLAY2\`;
    const mumuDeviceName = String.raw\`\\\\.\\DISPLAY27\`;
    const todeskDeviceName = String.raw\`\\\\.\\DISPLAY18\`;
    globalThis.result = {
      physical: isWindowsPhysicalDetachedDisplayCandidate({
        deviceName: physicalDeviceName,
        deviceString: "AMD Radeon RX 6750 GRE 12GB",
        displayName: "H24E7",
        friendlyName: "H24E7",
        productCode: "SKG2431",
      }),
      mumuVirtual: isWindowsPhysicalDetachedDisplayCandidate({
        deviceName: mumuDeviceName,
        deviceString: "MuMu Virtual Display Adapter",
        displayName: "H24E7",
        friendlyName: "H24E7",
        productCode: "SKG2431",
      }),
      todeskVirtual: isWindowsPhysicalDetachedDisplayCandidate({
        deviceName: todeskDeviceName,
        deviceString: "Todesk Virtual Display Adapter",
        displayName: "Todesk Virtual Display Adapter",
        friendlyName: "",
        productCode: "tdIdd",
      }),
    };
  `;
  const context = {};
  vm.runInNewContext(script, context);

  assert.equal(context.result.physical, true);
  assert.equal(context.result.mumuVirtual, false);
  assert.equal(context.result.todeskVirtual, false);
  assert.match(mainSource, /!isWindowsPhysicalDetachedDisplayCandidate\(topologyDisplay\)/u);
}

function verifyWindowsSwitchVerificationBehavior() {
  const mainSource = fs.readFileSync(path.resolve(__dirname, "..", "src", "main.js"), "utf8");
  const helperSource = ["normalizeText", "classifyWindowsSwitchVerification"]
    .map((name) => extractFunction(mainSource, name))
    .join("\n");
  const script = `
    ${helperSource}
    globalThis.result = {
      confirmed: classifyWindowsSwitchVerification([16], 16, ""),
      explicitMismatch: classifyWindowsSwitchVerification([16], 15, ""),
      readbackLost: classifyWindowsSwitchVerification([16], null, "No physical monitor handles"),
    };
  `;
  const context = {};
  vm.runInNewContext(script, context);

  assert.equal(context.result.confirmed.status, "confirmed");
  assert.equal(context.result.explicitMismatch.status, "unconfirmed");
  assert.equal(context.result.readbackLost.status, "accepted");
  assert.equal(context.result.readbackLost.error, "No physical monitor handles");
}

function verifyWindowsDisconnectedConfigPruningBehavior() {
  const mainSource = fs.readFileSync(path.resolve(__dirname, "..", "src", "main.js"), "utf8");
  const helperSource = [
    "normalizeText",
    "getStoredMonitorConfigMatchScore",
    "getWindowsMonitorDeviceKey",
    "isWindowsPhysicalDetachedDisplayCandidate",
    "shouldPreserveDisconnectedMonitorConfig",
  ]
    .map((name) => extractFunction(mainSource, name))
    .join("\n");
  const script = `
    const process = { platform: "win32" };
    const runtimes = new Map();
    function getExistingMonitorDesktopRuntime(id) { return runtimes.get(id) || null; }
    function isUserCustomizedMonitorConfig(config) { return Boolean(config.customized); }
    function hasMacPersistableMonitorIdentity() { return false; }
    function buildMacHardwareDisplayKey() { return ""; }
    ${helperSource}
    const physical = {
      deviceName: String.raw\`\\\\.\\DISPLAY2\`,
      deviceString: "AMD Radeon RX 6750 GRE 12GB",
      displayName: "H24E7",
      friendlyName: "H24E7",
      productCode: "SKG2431",
      attached: false,
    };
    const virtual = {
      ...physical,
      deviceName: String.raw\`\\\\.\\DISPLAY27\`,
      deviceString: "MuMu Virtual Display Adapter",
    };
    const physicalConfig = { id: "physical", match: { gdiDeviceName: physical.deviceName } };
    const virtualConfig = { id: "virtual", match: { gdiDeviceName: virtual.deviceName } };
    globalThis.result = {
      physicalDetached: shouldPreserveDisconnectedMonitorConfig(physicalConfig, [physical, virtual]),
      virtualDetached: shouldPreserveDisconnectedMonitorConfig(virtualConfig, [physical, virtual]),
      attachedDuplicate: shouldPreserveDisconnectedMonitorConfig(physicalConfig, [
        { ...physical, attached: true },
      ]),
      missingDefault: shouldPreserveDisconnectedMonitorConfig(physicalConfig, [virtual]),
      missingCustomized: shouldPreserveDisconnectedMonitorConfig(
        { ...physicalConfig, customized: true },
        [virtual]
      ),
      stableIdentityMatch: getStoredMonitorConfigMatchScore(
        {
          id: "stable",
          displayKey: "old-key",
          match: { windowsDisplayDeviceId: String.raw\`MONITOR\\SKG2431\\INSTANCE-A\` },
        },
        {
          displayKey: "new-key",
          windowsDisplayDeviceId: String.raw\`monitor\\skg2431\\instance-a\`,
        }
      ),
      stableIdentityMismatch: getStoredMonitorConfigMatchScore(
        {
          id: "stale",
          displayKey: "win:display1",
          match: {
            windowsDisplayDeviceId: String.raw\`MONITOR\\SKG2431\\INSTANCE-OLD\`,
            gdiDeviceName: physical.deviceName,
          },
        },
        {
          displayKey: "win:display1",
          windowsDisplayDeviceId: String.raw\`MONITOR\\SKG2431\\INSTANCE-NEW\`,
          gdiDeviceName: physical.deviceName,
        }
      ),
    };
  `;
  const context = {};
  vm.runInNewContext(script, context);

  assert.equal(context.result.physicalDetached, true);
  assert.equal(context.result.virtualDetached, false);
  assert.equal(context.result.attachedDuplicate, false);
  assert.equal(context.result.missingDefault, false);
  assert.equal(context.result.missingCustomized, true);
  assert.ok(context.result.stableIdentityMatch >= 200);
  assert.equal(context.result.stableIdentityMismatch, 0);
}

function verifyWindowsDetachedIdentityRefreshBehavior() {
  const mainSource = fs.readFileSync(path.resolve(__dirname, "..", "src", "main.js"), "utf8");
  const helperSource = [
    "normalizeText",
    "createWindowsDetachedDisplaySummary",
    "createWindowsDetachedTakeoverContext",
  ]
    .map((name) => extractFunction(mainSource, name))
    .join("\n");
  const script = `
    function getWindowsUsableDetachedDisplayName(display) {
      return normalizeText(display?.displayName);
    }
    function getMonitorDisplayName(config) {
      return normalizeText(config?.displayName);
    }
    function normalizeMonitorConfig(config) { return config; }
    ${helperSource}
    globalThis.result = createWindowsDetachedTakeoverContext(
      {
        id: "shared-screen",
        displayKey: String.raw\`win:\\\\.\\DISPLAY2\`,
        roleLabel: "共享屏幕",
        displayName: "H24E7",
        match: {
          windowsDisplayDeviceId: String.raw\`MONITOR\\SKG2431\\INSTANCE-A\`,
          gdiDeviceName: String.raw\`\\\\.\\DISPLAY2\`,
          productCode: "SKG2431",
        },
      },
      {
        deviceName: String.raw\`\\\\.\\DISPLAY9\`,
        displayDeviceId: String.raw\`MONITOR\\SKG2431\\INSTANCE-A\`,
        displayName: "H24E7",
        productCode: "SKG2431",
        width: 2560,
        height: 1440,
      },
      "stored"
    );
  `;
  const context = {};
  vm.runInNewContext(script, context);

  assert.equal(context.result.id, "shared-screen");
  assert.equal(context.result.monitor.match.gdiDeviceName, String.raw`\\.\DISPLAY9`);
  assert.equal(
    context.result.monitor.displayKey,
    String.raw`win-device:monitor\skg2431\instance-a`
  );
  assert.equal(context.result.display.gdiDeviceName, String.raw`\\.\DISPLAY9`);
  assert.equal(context.result.display.roleLabel, "共享屏幕");
}

function verifyDiagnosticLogTrimming() {
  const mainSource = fs.readFileSync(path.resolve(__dirname, "..", "src", "main.js"), "utf8");
  const helperSource = [
    "formatDiagnosticError",
    "truncateDiagnosticLogText",
    "createDiagnosticLogEntry",
    "trimDiagnosticLogIfNeeded",
    "appendDiagnosticLog",
  ]
    .map((name) => extractFunction(mainSource, name))
    .join("\n");
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "monitor-input-switch-log-selftest-"));
  const logPath = path.join(tempDir, "app.log");

  try {
    fs.writeFileSync(logPath, "old topology failure\n".repeat(40000));
    const script = `
      const DIAGNOSTIC_LOG_MAX_BYTES = 64 * 1024;
      const DIAGNOSTIC_LOG_TAIL_BYTES = 24 * 1024;
      const DIAGNOSTIC_LOG_ENTRY_MAX_BYTES = 8 * 1024;
      function getDiagnosticLogPath() { return ${JSON.stringify(logPath)}; }
      ${helperSource}
      const initialRoll = trimDiagnosticLogIfNeeded(${JSON.stringify(logPath)});
      const oversizedEntry = createDiagnosticLogEntry("oversized", "X".repeat(1024 * 1024));
      let rollCount = initialRoll ? 1 : 0;
      let maxObservedBytes = fs.statSync(${JSON.stringify(logPath)}).size;
      for (let index = 0; index < 240; index += 1) {
        const beforeBytes = fs.statSync(${JSON.stringify(logPath)}).size;
        appendDiagnosticLog(
          \`event-\${index}\`,
          \`failure-\${index}:\${"y".repeat(4096)}\`
        );
        const currentBytes = fs.statSync(${JSON.stringify(logPath)}).size;
        if (currentBytes < beforeBytes) {
          rollCount += 1;
        }
        maxObservedBytes = Math.max(maxObservedBytes, currentBytes);
        if (currentBytes > DIAGNOSTIC_LOG_MAX_BYTES) {
          throw new Error(\`Log exceeded hard cap: \${currentBytes}\`);
        }
      }
      globalThis.result = {
        initialRoll,
        oversizedEntryBytes: Buffer.byteLength(oversizedEntry),
        rollCount,
        maxObservedBytes,
      };
    `;
    const context = { fs, path, Buffer, process };
    vm.runInNewContext(script, context);

    const rolledLog = fs.readFileSync(logPath, "utf8");
    assert.equal(context.result.initialRoll, true);
    assert.ok(context.result.oversizedEntryBytes <= 8 * 1024);
    assert.ok(context.result.rollCount >= 2);
    assert.ok(context.result.maxObservedBytes <= 64 * 1024);
    assert.ok(fs.statSync(logPath).size <= 64 * 1024);
    assert.deepEqual(fs.readdirSync(tempDir), ["app.log"]);
    assert.match(rolledLog, /Diagnostic log rolled from/u);
    assert.match(rolledLog, /event-239/u);
    assert.doesNotMatch(rolledLog, /old topology failure/u);
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
}

function verifyExplorerSignatureParsing() {
  const mainSource = fs.readFileSync(path.resolve(__dirname, "..", "src", "main.js"), "utf8");
  const helperSource = extractFunction(mainSource, "parseExplorerSignature");
  const script = `
    ${helperSource}
    globalThis.result = {
      normal: parseExplorerSignature('"explorer.exe","13216","Console","1","342,020 K"'),
      multiline: parseExplorerSignature(
        'header ignored\\r\\n"explorer.exe","99","Console","1","100 K"'
      ),
      missing: parseExplorerSignature('INFO: No tasks are running which match the specified criteria.'),
      malformed: parseExplorerSignature('"explorer.exe","not-a-pid"'),
    };
  `;
  const context = {};
  vm.runInNewContext(script, context);

  assert.equal(context.result.normal, "explorer:13216");
  assert.equal(context.result.multiline, "explorer:99");
  assert.equal(context.result.missing, null);
  assert.equal(context.result.malformed, null);
}

function verifyWindowsPowerShellScriptArgs() {
  const mainSource = fs.readFileSync(path.resolve(__dirname, "..", "src", "main.js"), "utf8");
  const helperSource = [
    "normalizeText",
    "shouldUseWindowsPowerShellTemp",
    "getWindowsPowerShellScriptArgs",
    "resolveHelperCommandInvocation",
    "getWindowsPowerShellExecutablePath",
  ]
    .map((name) => extractFunction(mainSource, name))
    .join("\n");
  const script = `
    const process = { platform: "win32", env: { SystemRoot: "C:\\\\Windows" } };
    const fs = { existsSync: () => true };
    function getBundledResourcePath(...segments) {
      return path.join("C:\\\\app\\\\resources", ...segments);
    }
    ${helperSource}
    const powershellArgs = getWindowsPowerShellScriptArgs(
      "C:\\\\helpers\\\\display-topology.ps1",
      ["-Summary"]
    );
    globalThis.result = JSON.stringify({
      powershellArgs,
      powershellInvocation: resolveHelperCommandInvocation("powershell.exe", powershellArgs),
      regularInvocation: resolveHelperCommandInvocation("tasklist.exe", ["/NH"]),
    });
  `;
  const context = { path };
  vm.runInNewContext(script, context);
  const result = JSON.parse(context.result);

  assert.deepEqual(result.powershellArgs, [
    "-NoLogo",
    "-NoProfile",
    "-NonInteractive",
    "-WindowStyle",
    "Hidden",
    "-ExecutionPolicy",
    "Bypass",
    "-File",
    "C:\\helpers\\display-topology.ps1",
    "-Summary",
  ]);
  assert.deepEqual(result.powershellInvocation, {
    file: "C:\\app\\resources\\windows\\hidden-process.exe",
    args: [
      "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
      ...result.powershellArgs,
    ],
  });
  assert.deepEqual(result.regularInvocation, {
    file: "tasklist.exe",
    args: ["/NH"],
  });
}

function verifyWindowsHiddenLauncher() {
  const projectRoot = path.resolve(__dirname, "..");
  const sourcePath = path.join(projectRoot, "native", "windows", "hidden-process.cs");
  const buildScriptPath = path.join(projectRoot, "scripts", "build-windows-hidden-process.js");
  const packageJson = JSON.parse(fs.readFileSync(path.join(projectRoot, "package.json"), "utf8"));
  const gitignore = fs.readFileSync(path.join(projectRoot, ".gitignore"), "utf8");
  const source = fs.readFileSync(sourcePath, "utf8");
  const buildScript = fs.readFileSync(buildScriptPath, "utf8");

  assert.match(source, /CreateProcessW/u);
  assert.match(source, /CreateNoWindow = 0x08000000/u);
  assert.match(source, /StartfUseShowWindow/u);
  assert.match(source, /ShowWindow = SwHide/u);
  assert.match(source, /StartfUseStdHandles/u);
  assert.match(source, /CreatePipe/u);
  assert.match(source, /SearchPathW/u);
  assert.match(source, /Task\.Factory\.StartNew/u);
  assert.doesNotMatch(source, /ProcessStartInfo|Process\.Start/u);
  assert.match(source, /QuoteArgument/u);
  assert.match(buildScript, /\/target:winexe/u);
  assert.match(buildScript, /\/platform:x64/u);
  assert.match(buildScript, /windowsHide: true/u);
  assert.equal(packageJson.scripts.prestart, "npm run build:windows-launcher");
  assert.equal(packageJson.scripts["predist:win"], "npm run build:windows-launcher");
  assert.match(gitignore, /resources\/windows\/hidden-process\.exe/u);

  if (process.platform !== "win32") {
    return;
  }

  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "monitor-hidden-launcher-selftest-"));
  const launcherPath = path.join(tempDir, "hidden-process.exe");
  const echoScriptPath = path.join(tempDir, "echo arguments.js");
  const expectedArguments = ["value with spaces", 'value"quote', "C:\\path with space\\"];

  try {
    execFileSync(process.execPath, [buildScriptPath, "--output", launcherPath], {
      encoding: "utf8",
      timeout: 30000,
      windowsHide: true,
    });
    assert.equal(fs.existsSync(launcherPath), true);
    assert.ok(fs.statSync(launcherPath).size >= 4096);

    fs.writeFileSync(
      echoScriptPath,
      'process.stdout.write(JSON.stringify(process.argv.slice(2)));\n'
    );
    const echoedArguments = JSON.parse(
      execFileSync(launcherPath, [process.execPath, echoScriptPath, ...expectedArguments], {
        encoding: "utf8",
        timeout: 10000,
        windowsHide: true,
      })
    );
    assert.deepEqual(echoedArguments, expectedArguments);

    const powershellPath = path.join(
      process.env.SystemRoot || "C:\\Windows",
      "System32",
      "WindowsPowerShell",
      "v1.0",
      "powershell.exe"
    );
    const powershellOutput = execFileSync(
      launcherPath,
      [
        powershellPath,
        "-NoLogo",
        "-NoProfile",
        "-NonInteractive",
        "-Command",
        '[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false); [Console]::Write("launcher-ok")',
      ],
      {
        encoding: "utf8",
        timeout: 10000,
        windowsHide: true,
      }
    );
    assert.equal(powershellOutput, "launcher-ok");
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
}

async function verifyWindowsTopologyCacheBehavior() {
  const mainSource = fs.readFileSync(path.resolve(__dirname, "..", "src", "main.js"), "utf8");
  const helperSource = ["cloneWindowsTopologyDisplays", "getCachedWindowsTopologyDisplays"]
    .map((name) => extractFunction(mainSource, name))
    .join("\n");
  const script = `
    const WINDOWS_TOPOLOGY_CACHE_TTL_MS = 30 * 1000;
    let windowsTopologyCache = {
      fetchedAt: 1000,
      displays: [{ deviceName: "DISPLAY1", attached: true }],
    };
    ${helperSource}
    const fresh = getCachedWindowsTopologyDisplays(30_999);
    fresh[0].attached = false;
    globalThis.result = {
      freshLength: fresh.length,
      cacheStayedIsolated: windowsTopologyCache.displays[0].attached,
      boundaryLength: getCachedWindowsTopologyDisplays(31_000).length,
      expiredLength: getCachedWindowsTopologyDisplays(31_001).length,
      missingLength: (() => {
        windowsTopologyCache = { fetchedAt: 0, displays: [] };
        return getCachedWindowsTopologyDisplays(1000).length;
      })(),
    };
  `;
  const context = {};
  vm.runInNewContext(script, context);

  assert.equal(context.result.freshLength, 1);
  assert.equal(context.result.cacheStayedIsolated, true);
  assert.equal(context.result.boundaryLength, 1);
  assert.equal(context.result.expiredLength, 0);
  assert.equal(context.result.missingLength, 0);

  const topologySource = [
    "normalizeText",
    "normalizeWindowsTopologyDisplay",
    "cloneWindowsTopologyDisplays",
    "getCachedWindowsTopologyDisplays",
    "getWindowsTopologyDisplays",
  ]
    .map((name) => extractFunction(mainSource, name))
    .join("\n")
    .replace(
      "function getWindowsTopologyDisplays",
      "async function getWindowsTopologyDisplays"
    );
  const successfulOutput = JSON.stringify([
    {
      DeviceName: String.raw`\\.\DISPLAY1`,
      DisplayName: "H24E7",
      Attached: true,
      Primary: true,
      Width: 2560,
      Height: 1440,
    },
  ]);
  const asyncScript = `
    (async () => {
      const process = { platform: "win32" };
      const WINDOWS_TOPOLOGY_CACHE_TTL_MS = 30 * 1000;
      const WINDOWS_TOPOLOGY_FAILURE_BACKOFF_BASE_MS = 5000;
      const WINDOWS_TOPOLOGY_FAILURE_BACKOFF_MAX_MS = 60000;
      const WINDOWS_TOPOLOGY_LOG_INTERVAL_MS = 60 * 60 * 1000;
      const WINDOWS_TOPOLOGY_RECOVERY_LOG_THRESHOLD_MS = 60 * 1000;
      let windowsTopologyFailureCount = 0;
      let windowsTopologyRetryAfter = 0;
      let windowsTopologyFailureStartedAt = 0;
      let windowsTopologyCache = { fetchedAt: 0, displays: [] };
      let now = 1000;
      let helperMode = "success";
      const Date = { now: () => now };
      function appendDiagnosticLogRateLimited() {}
      function scheduleTrayRebuild() {}
      async function runWindowsTopologyCommand() {
        if (helperMode === "failure") {
          throw new Error("simulated topology failure");
        }
        return ${JSON.stringify(successfulOutput)};
      }
      ${topologySource}

      const initial = await getWindowsTopologyDisplays({ force: true });
      helperMode = "failure";
      now = 2000;
      const cached = await getWindowsTopologyDisplays({ force: true });
      cached[0].attached = false;
      const isolated = getCachedWindowsTopologyDisplays(now);
      now = 32_001;
      const expired = await getWindowsTopologyDisplays({ force: true });
      let strictFailure = "";
      try {
        await getWindowsTopologyDisplays({
          force: true,
          allowCachedOnFailure: false,
          throwOnFailure: true,
        });
      } catch (error) {
        strictFailure = error.message;
      }

      globalThis.result = {
        initialLength: initial.length,
        cachedLength: cached.length,
        cacheStayedIsolated: isolated[0].attached,
        expiredLength: expired.length,
        strictFailure,
      };
    })()
  `;
  const asyncContext = {};
  await vm.runInNewContext(asyncScript, asyncContext);
  assert.equal(asyncContext.result.initialLength, 1);
  assert.equal(asyncContext.result.cachedLength, 1);
  assert.equal(asyncContext.result.cacheStayedIsolated, true);
  assert.equal(asyncContext.result.expiredLength, 0);
  assert.match(asyncContext.result.strictFailure, /Windows 暂时无法读取显示拓扑/u);
}

function verifyLocalOnlyDocs() {
  const readmePath = path.resolve(__dirname, "..", "README.md");
  const handoffDocPath = path.resolve(__dirname, "..", "docs", "shared-monitor-handoff.md");
  const readme = fs.readFileSync(readmePath, "utf8");
  const handoffDoc = fs.readFileSync(handoffDocPath, "utf8");

  assert.match(readme, /127\.0\.0\.1/u);
  assert.match(readme, /hardware identity/u);
  assert.match(readme, /日常使用逻辑/u);
  assert.match(readme, /交给对方机器/u);
  assert.match(readme, /日常交给对方接口/u);
  assert.match(readme, /连接设备名/u);
  assert.match(readme, /接回 Windows 的共享屏/u);
  assert.match(readme, /灰色第二屏/u);
  assert.match(readme, /takeover candidates ignore known virtual display adapters/u);
  assert.match(readme, /write accepted, then readback disappeared/u);
  assert.match(readme, /single rolling file is hard-capped at 64 KiB/u);
  assert.match(readme, /retaining only the newest 24 KiB/u);
  assert.match(readme, /each entry is truncated to 8 KiB/u);
  assert.match(readme, /-WindowStyle Hidden/u);
  assert.match(readme, /hidden-process\.exe/u);
  assert.match(readme, /CREATE_NO_WINDOW/u);
  assert.match(readme, /Win32 display-device identity/u);
  assert.match(handoffDoc, /no LAN peer discovery/u);
  assert.match(handoffDoc, /Daily user model/u);
  assert.match(handoffDoc, /A gray second screen in Windows Settings is not treated as proof/u);
  assert.match(handoffDoc, /Per-interface device labels are optional presentation labels only/u);
  assert.match(handoffDoc, /configured daily peer interface is the actual target/u);
  assert.match(handoffDoc, /manual repair action do not blindly re-add a detached waiting screen/u);
  assert.match(handoffDoc, /takeover path first attaches the detached Windows display device/u);
  assert.match(handoffDoc, /hardware-bound/u);
  assert.match(handoffDoc, /same-model duplicate attached to Windows while its input is not that screen's configured local interface/u);
  assert.match(handoffDoc, /Known virtual display adapters/u);
  assert.match(handoffDoc, /successful write followed by complete DDC\/readback loss/u);
  assert.match(handoffDoc, /15-second fallback check runs only while a detached screen is waiting/u);
  assert.match(handoffDoc, /recent successful topology snapshot may be reused for at most 30 seconds/u);
  assert.match(handoffDoc, /Optional WMI friendly-name lookup/u);
  assert.match(handoffDoc, /explicit `-WindowStyle Hidden`/u);
  assert.match(handoffDoc, /hidden-process\.exe/u);
  assert.match(handoffDoc, /logical monitor's display-device identity/u);
  assert.match(
    handoffDoc,
    /controls only the external physical screens that are currently attached to the local host/u
  );
  assert.doesNotMatch(handoffDoc, /includes a first peer-confirmation layer/u);
  assert.doesNotMatch(handoffDoc, /ownership endpoint on the LAN/u);
  assert.doesNotMatch(handoffDoc, /discovered Windows peer/u);
  assert.doesNotMatch(handoffDoc, /confirmed mismatch after readback is a real switch failure/u);
  assert.doesNotMatch(handoffDoc, /readback still stays on the old input, the failure means/u);
}

function verifyPinnedMacDdcctlBuildScript() {
  const buildScriptPath = path.resolve(__dirname, "..", "scripts", "build-macos-ddcctl.sh");
  const ensureScriptPath = path.resolve(__dirname, "..", "scripts", "ensure-macos-ddcctl.sh");
  const buildScript = fs.readFileSync(buildScriptPath, "utf8");
  const ensureScript = fs.readFileSync(ensureScriptPath, "utf8");
  const gitignore = fs.readFileSync(path.resolve(__dirname, "..", ".gitignore"), "utf8");

  assert.match(buildScript, /DDCCTL_COMMIT="([0-9a-f]{40})"/u);
  assert.match(buildScript, /git -C "\$WORK_DIR" fetch --depth 1 origin "\$DDCCTL_COMMIT"/u);
  assert.match(buildScript, /printf '%s\\n' "\$DDCCTL_COMMIT" > "\$OUTPUT_STAMP"/u);
  assert.match(ensureScript, /EXPECTED_COMMIT=\$\(awk -F'"'/u);
  assert.match(ensureScript, /rev-parse HEAD/u);
  assert.match(ensureScript, /"\$OUTPUT_STAMP"/u);
  assert.match(gitignore, /resources\/bin\/ddcctl\.commit/u);
}

function verifyBuildScriptsUseUserTempWrapper() {
  const packageJson = JSON.parse(
    fs.readFileSync(path.resolve(__dirname, "..", "package.json"), "utf8")
  );
  const wrapperPath = path.resolve(__dirname, "with-user-temp.js");
  const wrapper = fs.readFileSync(wrapperPath, "utf8");

  assert.match(
    packageJson.scripts.dist,
    /node scripts\/with-user-temp\.js node node_modules\/electron-builder\/out\/cli\/cli\.js/u
  );
  assert.match(
    packageJson.scripts["dist:win"],
    /node scripts\/with-user-temp\.js node node_modules\/electron-builder\/out\/cli\/cli\.js --win/u
  );
  assert.match(
    packageJson.scripts.release,
    /node scripts\/with-user-temp\.js node node_modules\/electron-builder\/out\/cli\/cli\.js/u
  );
  assert.match(wrapper, /rawCommand === "node" \? process\.execPath : rawCommand/u);
  assert.doesNotMatch(wrapper, /shell:/u);
  assert.match(wrapper, /G72_INPUT_SWITCH_TEMP/u);
  assert.match(wrapper, /LOCALAPPDATA/u);
  assert.match(wrapper, /TEMP: tempRoot/u);
  assert.match(wrapper, /TMP: tempRoot/u);
  assert.match(wrapper, /TMPDIR: tempRoot/u);
}

function verifyWindowsHelperSourceGuards() {
  const topologyScript = fs.readFileSync(
    path.resolve(__dirname, "..", "resources", "windows", "display-topology.ps1"),
    "utf8"
  );
  const setInputScript = fs.readFileSync(
    path.resolve(__dirname, "..", "resources", "windows", "set-input.ps1"),
    "utf8"
  );

  assert.match(topologyScript, /PromotePrimaryAwayFromDisplay/u);
  assert.match(topologyScript, /ApplyPrimaryDisplayWithStableLayout/u);
  assert.match(topologyScript, /display\.PositionX - offsetX/u);
  assert.match(topologyScript, /display\.PositionY - offsetY/u);
  assert.match(topologyScript, /preferredModeDisplayEntry/u);
  assert.match(topologyScript, /resolvedPreferredWidth/u);
  assert.match(topologyScript, /RollbackDisplayModes/u);
  assert.match(topologyScript, /DisplayDeviceId/u);
  assert.match(topologyScript, /-DisplayDeviceId \$resolvedDisplayDeviceId/u);
  assert.match(topologyScript, /\[Console\]::OutputEncoding = \$Utf8NoBom/u);
  assert.match(topologyScript, /\[Console\]::Error\.WriteLine\(\$message\.Trim\(\)\)/u);
  assert.match(
    topologyScript,
    /try \{[\s\S]{0,240}Get-CimInstance -Namespace root\\wmi -ClassName WmiMonitorID -ErrorAction Stop[\s\S]{0,160}catch \{\s*return \$friendlyNameMap/u
  );
  assert.match(topologyScript, /Test-Path -LiteralPath \$cachePath -ErrorAction Stop/u);
  assert.match(topologyScript, /Cache enrichment is optional and must not block topology actions/u);
  assert.match(setInputScript, /\[switch\]\$ProbeDdc/u);
  assert.match(setInputScript, /\[Console\]::OutputEncoding = \$Utf8NoBom/u);
  assert.match(setInputScript, /physicalMonitorCount/u);
  assert.match(setInputScript, /probeScope = "physicalMonitorHandle"/u);
  assert.doesNotMatch(setInputScript, /capabilitiesAvailable/u);
}

function verifyCiWorkflowTriggers() {
  const workflowPath = path.resolve(__dirname, "..", ".github", "workflows", "release.yml");
  const workflow = fs.readFileSync(workflowPath, "utf8");

  assert.match(workflow, /pull_request:/u);
  assert.match(workflow, /branches:\s*\n\s*- main/u);
  assert.match(workflow, /tags:\s*\n\s*- "v\*"/u);
  assert.match(workflow, /permissions:\s*\n\s*contents: read/u);
  assert.match(workflow, /create-release:/u);
  assert.match(workflow, /release-windows:/u);
  assert.match(workflow, /release-macos:/u);
  assert.match(workflow, /finalize-release:/u);
  assert.match(workflow, /contents: write/u);
  assert.match(workflow, /gh release upload/u);
  assert.match(workflow, /gh release create[\s\S]{0,200}--draft/u);
  assert.match(workflow, /gh release edit[\s\S]{0,160}--draft=false --latest/u);
  assert.match(workflow, /Verify tag matches package version/u);
  assert.match(workflow, /npm run dist:win/u);
  assert.match(workflow, /npm run dist:mac/u);
  assert.doesNotMatch(workflow, /npm run release/u);
}

function findPowerShellCommand() {
  for (const command of ["pwsh", "powershell.exe"]) {
    try {
      execFileSync(command, ["-NoProfile", "-Command", "$PSVersionTable.PSVersion.ToString()"], {
        stdio: "pipe",
        encoding: "utf8",
      });
      return command;
    } catch {
      // Try the next PowerShell executable.
    }
  }

  return null;
}

function verifyWindowsScriptSyntax(powerShellCommand) {
  const topologyScriptPath = path.resolve(
    __dirname,
    "..",
    "resources",
    "windows",
    "display-topology.ps1"
  );
  const setInputScriptPath = path.resolve(
    __dirname,
    "..",
    "resources",
    "windows",
    "set-input.ps1"
  );
  const syntaxCheckCommand = `
$ErrorActionPreference = 'Stop'
$scripts = @(
  '${topologyScriptPath.replace(/'/gu, "''")}',
  '${setInputScriptPath.replace(/'/gu, "''")}'
)
foreach ($script in $scripts) {
  $tokens = $null
  $errors = $null
  [System.Management.Automation.Language.Parser]::ParseFile($script, [ref]$tokens, [ref]$errors) | Out-Null
  if ($errors.Count -gt 0) {
    throw ($errors | ForEach-Object { $_.Message } | Out-String)
  }
}
`;

  execFileSync(powerShellCommand, ["-NoProfile", "-Command", syntaxCheckCommand], {
    stdio: "pipe",
    encoding: "utf8",
  });
}

function readPlistJson(plistPath) {
  return JSON.parse(run("/usr/bin/plutil", ["-convert", "json", "-o", "-", plistPath]));
}

function isMacPathHidden(appPath) {
  try {
    if (run("/usr/bin/mdls", ["-name", "kMDItemFSInvisible", "-raw", appPath]) === "1") {
      return true;
    }
  } catch {
    // Fall through to filesystem flags below.
  }

  try {
    return run("/usr/bin/stat", ["-f", "%Sf", appPath]).split(",").includes("hidden");
  } catch {
    return false;
  }
}

function verifyMacHelperApps(appBundlePath) {
  if (!fs.existsSync(appBundlePath)) {
    throw new Error(`App bundle not found: ${appBundlePath}`);
  }

  const frameworksDir = path.join(appBundlePath, "Contents", "Frameworks");
  const helperApps = fs
    .readdirSync(frameworksDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && entry.name.endsWith(".app"))
    .map((entry) => entry.name)
    .sort();

  assert.deepEqual(helperApps, [
    "显示器输入切换 Helper (GPU).app",
    "显示器输入切换 Helper (Plugin).app",
    "显示器输入切换 Helper (Renderer).app",
    "显示器输入切换 Helper.app",
  ]);

  for (const helperName of helperApps) {
    const helperPath = path.join(frameworksDir, helperName);
    const plistPath = path.join(helperPath, "Contents", "Info.plist");
    const iconPath = path.join(helperPath, "Contents", "Resources", "icon.icns");
    const plist = readPlistJson(plistPath);

    assert.equal(plist.CFBundleIconFile, "icon.icns");
    assert.equal(fs.existsSync(iconPath), true, `${iconPath} should exist`);
    assert.equal(isMacPathHidden(helperPath), true);
    assert.match(plist.CFBundleName, /^显示器输入切换 Helper/u);
  }

  const bundledDdcctlPath = path.join(
    appBundlePath,
    "Contents",
    "Resources",
    "resources",
    "bin",
    "ddcctl"
  );
  assert.equal(
    fs.existsSync(bundledDdcctlPath),
    true,
    `${bundledDdcctlPath} should exist`
  );

  const bundledWindowsTopologyHelperPath = path.join(
    appBundlePath,
    "Contents",
    "Resources",
    "resources",
    "windows",
    "display-topology.ps1"
  );
  assert.equal(
    fs.existsSync(bundledWindowsTopologyHelperPath),
    true,
    `${bundledWindowsTopologyHelperPath} should exist`
  );
}

function writeFakeDdcctlBinary(fakeBinaryPath, mode) {
  const script = `#!/bin/sh
set -eu
if [ "\${1:-}" = "-h" ]; then
  if [ "${mode}" = "missing-count" ]; then
    cat <<'EOF'
Usage:
ddcctl    -d <1-..> [display#]
EOF
  else
    cat <<'EOF'
Usage:
ddcctl    -d <1-..> [display#]
I: found 1 external display
EOF
  fi
  exit 0
fi

if [ "\${1:-}" = "-d" ] && [ "\${2:-}" = "1" ] && [ "\${3:-}" = "-i" ] && [ "\${4:-}" = "16" ]; then
  echo "OK"
  exit 0
fi

if [ "\${1:-}" = "-d" ] && [ "\${2:-}" = "1" ] && [ "\${3:-}" = "-i" ] && [ "\${4:-}" = "?" ]; then
  if [ "${mode}" = "matched" ]; then
    echo "VCP 0x60 current: 16 max: 18"
  elif [ "${mode}" = "query-fails" ]; then
    echo "readback unavailable" >&2
    exit 1
  else
    echo "VCP 0x60 current: 6 max: 18"
  fi
  exit 0
fi

echo "unexpected args: $*" >&2
exit 1
`;

  fs.writeFileSync(fakeBinaryPath, script, { mode: 0o755 });
}

function verifyMacDdcctlFallbackScript() {
  const switchScriptPath = path.resolve(
    __dirname,
    "..",
    "resources",
    "mac",
    "switch-input.sh"
  );
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "monitor-input-switch-selftest-"));
  const fakeBinaryPath = path.join(tempDir, "fake-ddcctl");
  const baseEnv = {
    ...process.env,
    DISPLAY_NAME: "Local Monitor",
    DISPLAY_INDEX: "1",
    DISABLE_BETTERDISPLAY: "1",
    BUNDLED_DDCCTL_PATH: fakeBinaryPath,
    PATH: "/usr/bin:/bin:/usr/sbin:/sbin",
  };

  writeFakeDdcctlBinary(fakeBinaryPath, "matched");
  execFileSync("/bin/sh", [switchScriptPath, "16"], {
    env: baseEnv,
    stdio: "pipe",
    encoding: "utf8",
  });

  writeFakeDdcctlBinary(fakeBinaryPath, "unchanged");
  const mismatchOutput = execFileSync("/bin/sh", [switchScriptPath, "16"], {
    env: baseEnv,
    stdio: "pipe",
    encoding: "utf8",
  });
  assert.match(mismatchOutput, /UNCONFIRMED/u);

  const probeOutput = execFileSync("/bin/sh", [switchScriptPath, "--probe-ddc"], {
    env: baseEnv,
    stdio: "pipe",
    encoding: "utf8",
  }).trim();
  assert.equal(probeOutput, "OK");

  writeFakeDdcctlBinary(fakeBinaryPath, "query-fails");
  const unconfirmedOutput = execFileSync("/bin/sh", [switchScriptPath, "16"], {
    env: baseEnv,
    stdio: "pipe",
    encoding: "utf8",
  });
  assert.match(unconfirmedOutput, /UNCONFIRMED/u);

  writeFakeDdcctlBinary(fakeBinaryPath, "missing-count");
  let queryFailure = null;
  try {
    execFileSync("/bin/sh", [switchScriptPath, "--query-input"], {
      env: baseEnv,
      stdio: "pipe",
      encoding: "utf8",
    });
  } catch (error) {
    queryFailure = error;
  }

  assert.ok(queryFailure, "ddcctl query fallback should fail closed when display count is unknown");
  assert.match(
    `${queryFailure.stderr || queryFailure.message}`,
    /ddcctl 没有可靠返回外接屏数量/u
  );

  let missingCountFailure = null;
  try {
    execFileSync("/bin/sh", [switchScriptPath, "16"], {
      env: baseEnv,
      stdio: "pipe",
      encoding: "utf8",
    });
  } catch (error) {
    missingCountFailure = error;
  }

  assert.ok(missingCountFailure, "ddcctl switch fallback should fail closed when display count is unknown");
  assert.match(
    `${missingCountFailure.stderr || missingCountFailure.message}`,
    /ddcctl 没有可靠返回外接屏数量/u
  );
}

function writeFakeBetterDisplayBinary(fakeBinaryPath, mode = "normal") {
  const script = `#!/bin/sh
set -eu

joined="$*"

case "$joined" in
  get*" -displayID=777 "*|get*" -displayID=777")
    echo "display id not found" >&2
    exit 1
    ;;
  set*" -displayID=777 "*|set*" -displayID=777")
    echo "display id not found" >&2
    exit 1
    ;;
  set*" -nameLike=Fallback Monitor "*" -vcp=inputSelect "*|set*" -nameLike=Fallback Monitor"*" -vcp=inputSelect")
    echo "OK"
    exit 0
    ;;
  get*" -nameLike=Fallback Monitor "*" -vcp=inputSelect "*|get*" -nameLike=Fallback Monitor"*" -vcp=inputSelect")
    if [ "${mode}" = "write-only" ]; then
      echo "readback unavailable" >&2
      exit 1
    fi
    echo "16"
    exit 0
    ;;
  set*" -nameLike=Fallback Monitor "*" -vcp=0x60 "*|set*" -nameLike=Fallback Monitor"*" -vcp=0x60")
    echo "OK"
    exit 0
    ;;
  get*" -nameLike=Fallback Monitor "*" -vcp=0x60 "*|get*" -nameLike=Fallback Monitor"*" -vcp=0x60")
    if [ "${mode}" = "write-only" ]; then
      echo "readback unavailable" >&2
      exit 1
    fi
    echo "16"
    exit 0
    ;;
esac

echo "unexpected args: $*" >&2
exit 1
`;

  fs.writeFileSync(fakeBinaryPath, script, { mode: 0o755 });
}

function verifyMacBetterDisplayFallbackScript() {
  const switchScriptPath = path.resolve(
    __dirname,
    "..",
    "resources",
    "mac",
    "switch-input.sh"
  );
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "monitor-input-switch-bd-selftest-"));
  const fakeBinaryPath = path.join(tempDir, "fake-betterdisplay");
  const baseEnv = {
    ...process.env,
    DISPLAY_NAME: "Fallback Monitor",
    DISPLAY_ID: "777",
    DISPLAY_NAME_FALLBACK_ALLOWED: "1",
    BETTERDISPLAY_APP_PATH: fakeBinaryPath,
    BUNDLED_DDCCTL_PATH: path.join(tempDir, "missing-ddcctl"),
    PATH: "/usr/bin:/bin:/usr/sbin:/sbin",
  };

  writeFakeBetterDisplayBinary(fakeBinaryPath);

  execFileSync("/bin/sh", [switchScriptPath, "16"], {
    env: baseEnv,
    stdio: "pipe",
    encoding: "utf8",
  });

  const queryOutput = execFileSync("/bin/sh", [switchScriptPath, "--query-input"], {
    env: baseEnv,
    stdio: "pipe",
    encoding: "utf8",
  }).trim();

  assert.equal(queryOutput, "16");
}

function verifyMacBetterDisplayWriteOnlyProbeScript() {
  const switchScriptPath = path.resolve(
    __dirname,
    "..",
    "resources",
    "mac",
    "switch-input.sh"
  );
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "monitor-input-switch-bd-writeonly-selftest-"));
  const fakeBinaryPath = path.join(tempDir, "fake-betterdisplay");
  const baseEnv = {
    ...process.env,
    DISPLAY_NAME: "Fallback Monitor",
    DISPLAY_ID: "777",
    DISPLAY_NAME_FALLBACK_ALLOWED: "1",
    BETTERDISPLAY_APP_PATH: fakeBinaryPath,
    BUNDLED_DDCCTL_PATH: path.join(tempDir, "missing-ddcctl"),
    PATH: "/usr/bin:/bin:/usr/sbin:/sbin",
  };

  writeFakeBetterDisplayBinary(fakeBinaryPath, "write-only");

  const probeOutput = execFileSync("/bin/sh", [switchScriptPath, "--probe-ddc"], {
    env: baseEnv,
    stdio: "pipe",
    encoding: "utf8",
  }).trim();
  assert.equal(probeOutput, "UNKNOWN");

  const switchOutput = execFileSync("/bin/sh", [switchScriptPath, "16"], {
    env: baseEnv,
    stdio: "pipe",
    encoding: "utf8",
  });
  assert.match(switchOutput, /UNCONFIRMED/u);
}

function verifyMacHelperAppsIfAvailable() {
  if (process.env.SELF_VERIFY_REQUIRE_MAC_APP_BUNDLE !== "1") {
    return;
  }

  const builtAppPath = path.resolve(
    __dirname,
    "..",
    "release",
    "mac-arm64",
    "显示器输入切换.app"
  );
  if (fs.existsSync(builtAppPath)) {
    verifyMacHelperApps(builtAppPath);
    return;
  }

  if (process.env.SELF_VERIFY_ALLOW_INSTALLED_MAC_APP_BUNDLE !== "1") {
    throw new Error(`No built macOS app bundle was found: ${builtAppPath}`);
  }

  const installedAppPath = "/Applications/显示器输入切换.app";
  if (fs.existsSync(installedAppPath)) {
    verifyMacHelperApps(installedAppPath);
    return;
  }

  throw new Error("No macOS app bundle was found for self verification.");
}

async function main() {
  verifyMainSourceSyntax();
  verifyMainSourceBusinessGuards();
  verifyMacMonitorConfigSyncBehavior();
  verifyStrictIntegerParsing();
  verifyMonitorConfigFormRejectsInvalidInputValues();
  verifyWindowsDetachedVirtualDisplaysRejected();
  verifyWindowsSwitchVerificationBehavior();
  verifyWindowsDisconnectedConfigPruningBehavior();
  verifyWindowsDetachedIdentityRefreshBehavior();
  verifyExplorerSignatureParsing();
  verifyWindowsPowerShellScriptArgs();
  verifyWindowsHiddenLauncher();
  await verifyWindowsTopologyCacheBehavior();
  verifyDiagnosticLogTrimming();
  verifyLocalOnlyDocs();
  verifyPinnedMacDdcctlBuildScript();
  verifyBuildScriptsUseUserTempWrapper();
  verifyWindowsHelperSourceGuards();
  verifyCiWorkflowTriggers();

  const powerShellCommand = findPowerShellCommand();
  if (powerShellCommand) {
    verifyWindowsScriptSyntax(powerShellCommand);
  }

  if (process.platform === "darwin") {
    verifyMacDdcctlFallbackScript();
    verifyMacBetterDisplayFallbackScript();
    verifyMacBetterDisplayWriteOnlyProbeScript();
    verifyMacHelperAppsIfAvailable();
  }

  process.stdout.write("Self verification passed.\n");
}

main().catch((error) => {
  process.stderr.write(`${error?.stack || error}\n`);
  process.exitCode = 1;
});
