"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");
const vm = require("node:vm");
const { execFileSync } = require("node:child_process");

function run(command, args) {
  return execFileSync(command, args, { encoding: "utf8" }).trim();
}

function verifyMainSourceSyntax() {
  execFileSync(process.execPath, ["--check", path.resolve(__dirname, "..", "src", "main.js")], {
    stdio: "pipe",
    encoding: "utf8",
  });
}

function verifyMainSourceBusinessGuards() {
  const mainSourcePath = path.resolve(__dirname, "..", "src", "main.js");
  const mainSource = fs.readFileSync(mainSourcePath, "utf8");

  assert.match(
    mainSource,
    /verificationStatus === "confirmed"[\s\S]*detachWindowsDisplayForMonitor/u
  );
  assert.match(mainSource, /MAC_DISPLAY_METADATA_CACHE_TTL_MS = 5000/u);
  assert.match(mainSource, /screen\.getPrimaryDisplay\(\)\?\.id/u);
  assert.match(mainSource, /DISPLAY_NAME_FALLBACK_ALLOWED: displaySummary\.displayNameIsUnique \? "1" : "0"/u);
  assert.match(mainSource, /const resolvedMonitorId = normalizeText\(matchingMonitorConfig\?\.id\) \|\| displaySummary\.id;/u);
  assert.match(mainSource, /singleMacSoftMatchAllowed/u);
  assert.match(mainSource, /function shouldAllowSingleMacSoftDisplayMatch/u);
  assert.match(mainSource, /function isSingleMacSoftDisplayMatch/u);
  assert.match(mainSource, /function buildMacSoftDisplayKey/u);
  assert.match(mainSource, /function withDisplayNameUniqueness/u);
  assert.match(mainSource, /async function attemptPendingWindowsRestores\(\{\s*monitorId: targetMonitorId = null,\s*displaySummaries = null,/u);
  assert.match(mainSource, /allowAttachDetached = false/u);
  assert.match(mainSource, /allowAttachDetached: true/u);
  assert.match(mainSource, /const windowsTakeoverInProgressMonitorIds = new Set\(\)/u);
  assert.match(mainSource, /const windowsTakeoverProtectedUntilByMonitorId = new Map\(\)/u);
  assert.match(mainSource, /WINDOWS_TAKEOVER_SETTLE_MS = 45000/u);
  assert.match(mainSource, /async function attemptWindowsDuplicateForeignDisplayDetaches/u);
  assert.match(mainSource, /function getWindowsDuplicateDisplayIdentityKey/u);
  assert.match(mainSource, /function isWindowsInputValueForTarget/u);
  assert.match(mainSource, /function isWindowsInputValueForConfiguredExternalHandoffTarget/u);
  assert.match(mainSource, /function isExternalWindowsHandoffTargetId/u);
  assert.doesNotMatch(mainSource, /differs from configured local input/u);
  assert.match(mainSource, /isWindowsTakeoverInProgress\(monitorConfig\)/u);
  assert.match(mainSource, /function isWindowsTakeoverInProgress/u);
  assert.match(mainSource, /function markWindowsTakeoverProtection/u);
  assert.match(mainSource, /function killProcessTree/u);
  assert.match(mainSource, /taskkill\.exe/u);
  assert.match(mainSource, /稳定保留这块屏/u);
  assert.match(mainSource, /stableMs = 0/u);
  assert.match(mainSource, /WINDOWS_TOPOLOGY_COMMAND_TIMEOUT_MS/u);
  assert.match(mainSource, /WINDOWS_DDC_PROBE_TIMEOUT_MS/u);
  assert.match(mainSource, /!shouldUseWindowsDisplayHandoffForMonitor\(monitorConfig, attachedDisplays\.length\)/u);
  assert.match(mainSource, /pendingAwayAndUnverified/u);
  assert.match(mainSource, /async function takeoverWindowsDetachedMonitor/u);
  assert.match(mainSource, /function getWindowsDetachedTakeoverContexts/u);
  assert.match(mainSource, /function getWindowsHeuristicDetachedTakeoverDisplays/u);
  assert.match(mainSource, /function pruneRedundantWindowsHeuristicTakeoverConfigs/u);
  assert.match(mainSource, /const hasExplicitDetachedConfig = storedMonitorConfigs\.some/u);
  assert.match(mainSource, /pruneRedundantWindowsHeuristicTakeoverConfigs\(\s*connectedMonitorIds,\s*resolvedTopologyDisplays/u);
  assert.match(mainSource, /function isWindowsAutoGeneratedTakeoverConfig/u);
  assert.match(mainSource, /function renderWindowsTakeoverSection/u);
  assert.match(mainSource, /function getUsageIntroText/u);
  assert.match(mainSource, /function renderUsageGuide/u);
  assert.match(mainSource, /function renderDailyVisibleMonitorActions/u);
  assert.match(mainSource, /function getPreferredPeerTargetId/u);
  assert.match(mainSource, /function getConfiguredPeerInterfaceId/u);
  assert.match(mainSource, /peerInterfaceId: parseTargetId/u);
  assert.match(mainSource, /日常交给对方接口/u);
  assert.doesNotMatch(mainSource, /configuredPeerTargetId/u);
  assert.match(mainSource, /日常逻辑/u);
  assert.match(mainSource, /灰色第二屏/u);
  assert.match(mainSource, /高级：单独切输入源 \/ 校准 DDC 值/u);
  assert.match(mainSource, /交给\$\{escapeHtml\(getPeerMachineLabel\(peerTargetId, monitorContext\.monitor\)\)\}/u);
  assert.match(mainSource, /deviceLabel: normalizeText/u);
  assert.match(mainSource, /连接设备名（可选）/u);
  assert.match(mainSource, /当前没有可接回共享屏/u);
  assert.match(mainSource, /待接回屏幕/u);
  assert.match(mainSource, /自动：交给对方时移出桌面，接回时恢复/u);
  assert.doesNotMatch(mainSource, /回来后自动接回/u);
  assert.doesNotMatch(mainSource, /Mac mini \/ 对方机器/u);
  assert.doesNotMatch(mainSource, /Windows 主动接管失败/u);
  assert.match(mainSource, /\/windows\/takeover\//u);
  assert.match(mainSource, /await attachWindowsDisplayForMonitor\(/u);
  assert.match(mainSource, /async function switchWindowsDisplayForMonitorConfig/u);
  assert.match(mainSource, /await switchWindowsDisplayForMonitorConfig\(monitorConfig, localTarget\)/u);
  assert.match(mainSource, /function formatWindowsTakeoverError/u);
  assert.match(mainSource, /不向 Windows 暴露控制句柄/u);
  assert.match(mainSource, /"-GdiDeviceName",\s*deviceName/u);
  assert.match(mainSource, /normalizeText\(monitorConfig\?\.match\?\.gdiDeviceName\)/u);
  assert.match(mainSource, /const externalDisplays = orderedDisplays\.filter\(\(display\) => !display\.internal\);/u);
  assert.match(
    mainSource,
    /\.filter\(\(\{ electronDisplay \}\) => Boolean\(electronDisplay\) && !electronDisplay\.internal\);/u
  );
  assert.match(mainSource, /startDisplayChangeWatcher\(\);/u);
  assert.match(mainSource, /screen\.on\("display-added", handleDisplayChange\);/u);
  assert.match(mainSource, /screen\.on\("display-metrics-changed", handleDisplayChange\);/u);
  assert.match(mainSource, /forceMacDisplayMetadataRefresh/u);
  assert.match(mainSource, /system_profiler", \["SPDisplaysDataType", "-json"\]/u);
  assert.match(mainSource, /monitorEntry\?\.\["_spdisplays_display-vendor-id"\]/u);
  assert.match(mainSource, /monitorEntry\?\.\["_spdisplays_display-product-id"\]/u);
  assert.match(mainSource, /monitorEntry\?\.\["_spdisplays_display-serial-number"\]/u);
  assert.doesNotMatch(mainSource, /monitorEntry\?\._spdisplays_display-vendor-id/u);
  assert.doesNotMatch(mainSource, /monitorEntry\?\._spdisplays_display-product-id/u);
  assert.doesNotMatch(mainSource, /monitorEntry\?\._spdisplays_display-serial-number/u);
  assert.match(mainSource, /function isMacProfilerDisplayResolutionMatch/u);
  assert.match(mainSource, /function doesWindowsElectronDisplayExactlyMatchTopology/u);
  assert.match(mainSource, /function doesWindowsElectronDisplaySizeMatchTopology/u);
  assert.match(mainSource, /function getStateBackupPath/u);
  assert.match(mainSource, /function normalizeWindowsRestoreLayout/u);
  assert.match(mainSource, /topologyDisplay\.primary/u);
  assert.match(
    mainSource,
    /await detachWindowsDisplayForMonitor\(\s*monitorConfig,\s*attachedDisplayCountBeforeSwitch,\s*buildWindowsRestoreLayout\(topologyDisplay\)\s*\)/u
  );
  assert.doesNotMatch(mainSource, /remainingMatches\.length === remainingDisplays\.length/u);
  assert.doesNotMatch(mainSource, /remainingMatches\[index\]\.electronDisplay = remainingDisplays\[index\]/u);
  assert.doesNotMatch(mainSource, /candidate\.width === display\?\.bounds\?\.width/u);
  assert.doesNotMatch(mainSource, /Skipping Windows desktop detach for primary display/u);
  assert.match(mainSource, /promoteWindowsPrimaryAwayBeforeSwitch/u);
  assert.match(mainSource, /-PromotePrimaryAwayFromMonitor/u);
  assert.match(mainSource, /getWindowsDdcProbeResultsByDeviceName/u);
  assert.match(mainSource, /attachMacDdcProbeResults/u);
  assert.match(mainSource, /function createDdcProbeSummary/u);
  assert.match(mainSource, /function isMonitorDirectSwitchEnabled/u);
  assert.match(mainSource, /ddcProbe: createDdcProbeSummary/u);
  assert.match(mainSource, /runtimeStatus\.ddcAvailable === false/u);
  assert.match(mainSource, /statusText = "当前不可控"/u);
  assert.doesNotMatch(mainSource, /return getMacDdcCapableDisplaySummaries\(externalDisplaySummaries\)/u);
  assert.match(mainSource, /statusText = "当前输入未知"/u);
  assert.doesNotMatch(mainSource, /statusText = "读取失败"/u);
  assert.doesNotMatch(mainSource, /没有真正切到/u);
  assert.match(mainSource, /timeout: HELPER_COMMAND_TIMEOUT_MS/u);
  assert.match(mainSource, /CURRENT_INPUT_COMMAND_TIMEOUT_MS = 5000/u);
  assert.match(mainSource, /timeout: CURRENT_INPUT_COMMAND_TIMEOUT_MS/u);
  assert.match(mainSource, /SYSTEM_PROFILER_COMMAND_TIMEOUT_MS = 45000/u);
  assert.match(mainSource, /LOCAL_REQUEST_BODY_LIMIT_BYTES = 64 \* 1024/u);
  assert.match(mainSource, /switchOperationQueue = Promise\.resolve\(\)/u);
  assert.match(mainSource, /switchInFlightByMonitorId/u);
  assert.match(mainSource, /async function switchMonitorUnlocked/u);
  assert.match(mainSource, /switchOperationQueue = switchTask\.catch\(\(\) => \{\}\)/u);
  assert.match(mainSource, /function shouldPreserveDisconnectedMonitorConfig/u);
  assert.match(mainSource, /process\.platform === "darwin"[\s\S]{0,120}hasMacPersistableMonitorIdentity/u);
  assert.match(mainSource, /function findStoredMonitorConfigForDisplay/u);
  assert.match(mainSource, /customizedMacSoftMatches\.length === 1/u);
  assert.match(mainSource, /function isUserCustomizedMonitorConfig/u);
  assert.match(mainSource, /function isUsableMacHardwareId/u);
  assert.match(mainSource, /function getMacPersistableMonitorIdentityKey/u);
  assert.match(mainSource, /function hasMacPersistableMonitorIdentity/u);
  assert.match(mainSource, /function isGenericMacDisplayName/u);
  assert.match(mainSource, /preservedMacIdentityKeys/u);
  assert.doesNotMatch(mainSource, /buildMacSoftDisplayKey\(monitorConfig\) \|\|\s*normalizeText\(monitorConfig\.displayKey\)/u);
  assert.match(mainSource, /function pruneStateForKnownMonitorIds/u);
  assert.match(mainSource, /function normalizePersistedSwitchOutcome/u);
  assert.match(mainSource, /function shouldClearPersistedSwitchOutcome/u);
  assert.match(mainSource, /lastSwitchOutcome: normalizePersistedSwitchOutcome/u);
  assert.match(mainSource, /outcomeMessage: successMessages\.outcomeMessage/u);
  assert.match(mainSource, /createHttpError\(413, "请求内容过大。"\)/u);
  assert.match(mainSource, /function getHealthConnectedMonitorSummaries/u);
  assert.match(mainSource, /connectedMonitors: getHealthConnectedMonitorSummaries\(\)/u);
  assert.doesNotMatch(
    mainSource,
    /requestUrl\.pathname === "\/health"[\s\S]{0,300}getConnectedMonitorContexts/u
  );
  assert.match(mainSource, /function parseLocalRequestUrl\(request\)/u);
  assert.match(mainSource, /`http:\/\/\$\{LOOPBACK_HOST\}:\$\{getListeningPort\(\)\}`/u);
  assert.match(mainSource, /function decodePathSegment\(value\)/u);
  assert.match(mainSource, /createHttpError\(400, "请求路径编码无效。"\)/u);
  assert.doesNotMatch(mainSource, /request\.headers\.host/u);
  assert.match(mainSource, /function shouldLogControlRequestError\(error\)/u);
  assert.match(mainSource, /if \(shouldLogControlRequestError\(error\)\) \{\s*appendDiagnosticLog\("Control request failed", error\);/u);
  assert.match(mainSource, /async function mapSequential\(items, mapper\)/u);
  assert.match(mainSource, /const probeResults = await mapSequential\(/u);
  assert.doesNotMatch(mainSource, /request\.destroy\(\)/u);
  assert.match(mainSource, /function hasMacPhysicalIdentity/u);
  assert.match(mainSource, /function hasMacSafeDdcTargetIdentity/u);
  assert.match(mainSource, /targetable-unconfirmed/u);
  assert.match(mainSource, /confirmed: ok && status === "ok"/u);
  assert.match(mainSource, /if \(forceRefresh\) \{\s*macDisplayMetadataCache = \{\s*fetchedAt: 0,\s*displays: \[\],\s*\};\s*return \[\];\s*\}/u);
  assert.doesNotMatch(mainSource, /:\s*displaySummary\.electronDisplayId/u);
  assert.match(mainSource, /function runSwitchCandidateSequence/u);
  assert.match(mainSource, /getExpectedProbeInputValues\(target\.inputValue, monitorContext\.monitor\)/u);
  assert.match(mainSource, /function parseStrictInteger/u);
}

function extractFunction(source, name) {
  const start = source.indexOf(`function ${name}`);
  assert.notEqual(start, -1, `Missing function ${name}`);
  const declarationEnd = source.indexOf(") {", start);
  const bodyStart = declarationEnd >= 0
    ? source.indexOf("{", declarationEnd)
    : source.indexOf("{", start);
  let depth = 0;

  for (let index = bodyStart; index < source.length; index += 1) {
    const char = source[index];
    if (char === "{") {
      depth += 1;
    } else if (char === "}") {
      depth -= 1;
      if (depth === 0) {
        return source.slice(start, index + 1);
      }
    }
  }

  throw new Error(`Could not extract function ${name}`);
}

function verifyMacMonitorConfigSyncBehavior() {
  const mainSourcePath = path.resolve(__dirname, "..", "src", "main.js");
  const mainSource = fs.readFileSync(mainSourcePath, "utf8");
  const functionNames = [
    "normalizeText",
    "parseTargetId",
    "getTarget",
    "getLocalInterfaceId",
    "getConfiguredPeerInterfaceId",
    "isUserCustomizedMonitorConfig",
    "hasMacPhysicalIdentity",
    "isUsableMacHardwareId",
    "buildMacHardwareDisplayKey",
    "buildMacSoftDisplayKey",
    "isSingleMacSoftDisplayMatch",
    "getMacPersistableMonitorIdentityKey",
    "isGenericMacDisplayName",
    "findStoredMonitorConfigForDisplay",
  ];
  const helperSource = functionNames.map((name) => extractFunction(mainSource, name)).join("\n");
  const script = `
    const TARGET_SLOTS = [
      { id: "dp1", title: "DP1", defaultInputValue: 15 },
      { id: "dp2", title: "DP2", defaultInputValue: 16 },
      { id: "hdmi1", title: "HDMI1", defaultInputValue: 17 },
      { id: "hdmi2", title: "HDMI2", defaultInputValue: 18 },
    ];
    const TARGET_SLOT_MAP = new Map(TARGET_SLOTS.map((slot) => [slot.id, slot]));
    const TARGET_IDS = TARGET_SLOTS.map((slot) => slot.id);
    ${helperSource}
    const displaySummary = {
      displayKey: "mac-system:2",
      detectedName: "H24E7",
      macVendorId: "4d67",
      macProductId: "2431",
      macSerialNumber: "1",
      macSystemDisplayId: 2,
      electronDisplayId: 2,
    };
    const staleDefault = {
      id: "monitor-new",
      displayKey: "mac-system:2",
      displayName: "H24E7",
      localInterfaceId: "dp1",
      peerInterfaceId: "",
      interfaces: {},
      match: { macVendorId: "4d67", macProductId: "2431", macSerialNumber: "1" },
    };
    const calibrated = {
      id: "monitor-old",
      displayKey: "mac-system:1",
      displayName: "H24E7",
      localInterfaceId: "hdmi1",
      peerInterfaceId: "dp2",
      interfaces: {},
      match: { macVendorId: "4d67", macProductId: "2431", macSerialNumber: "1" },
    };
    const blankShell = {
      id: "monitor-blank",
      displayKey: "mac:5",
      displayName: "",
      localInterfaceId: "dp1",
      peerInterfaceId: "",
      interfaces: {},
      match: {},
    };
    const virtualShell = {
      id: "monitor-virtual",
      displayKey: "mac-system:7",
      displayName: "spdisplays_display",
      localInterfaceId: "dp1",
      peerInterfaceId: "",
      interfaces: {},
      match: { macVendorId: "756e6b6e", macProductId: "76697274" },
    };
    globalThis.result = {
      matchId: findStoredMonitorConfigForDisplay(
        displaySummary,
        [staleDefault, calibrated, blankShell, virtualShell],
        new Set(),
        true
      ).id,
      calibratedIdentity: getMacPersistableMonitorIdentityKey(calibrated),
      blankIdentity: getMacPersistableMonitorIdentityKey(blankShell),
      virtualIdentity: getMacPersistableMonitorIdentityKey(virtualShell),
      virtualPhysical: hasMacPhysicalIdentity({
        macVendorId: "756e6b6e",
        macProductId: "76697274",
      }),
    };
  `;
  const context = { process: { platform: "darwin" } };
  vm.runInNewContext(script, context);
  assert.equal(context.result.matchId, "monitor-old");
  assert.match(context.result.calibratedIdentity, /^mac-soft:4d67:2431:h24e7$/u);
  assert.equal(context.result.blankIdentity, "");
  assert.equal(context.result.virtualIdentity, "");
  assert.equal(context.result.virtualPhysical, false);
}

function verifyStrictIntegerParsing() {
  const mainSourcePath = path.resolve(__dirname, "..", "src", "main.js");
  const mainSource = fs.readFileSync(mainSourcePath, "utf8");
  const functionNames = [
    "normalizeText",
    "parseStrictInteger",
    "normalizePositiveInteger",
    "normalizeDisplayIdentifier",
    "parseInputValue",
  ];
  const helperSource = functionNames.map((name) => extractFunction(mainSource, name)).join("\n");
  const script = `
    ${helperSource}
    globalThis.result = {
      validInput: parseInputValue("17"),
      paddedInput: parseInputValue(" 017 "),
      decimalInput: parseInputValue("17.5"),
      suffixInput: parseInputValue("17abc"),
      negativeInput: parseInputValue("-1"),
      blankInput: parseInputValue(""),
      fallbackValid: normalizePositiveInteger("42", 7),
      fallbackInvalid: normalizePositiveInteger("42px", 7),
      displayZero: normalizeDisplayIdentifier("0"),
      displayInvalid: normalizeDisplayIdentifier("1x"),
    };
  `;
  const context = {};
  vm.runInNewContext(script, context);
  assert.equal(context.result.validInput, 17);
  assert.equal(context.result.paddedInput, 17);
  assert.equal(Number.isNaN(context.result.decimalInput), true);
  assert.equal(Number.isNaN(context.result.suffixInput), true);
  assert.equal(Number.isNaN(context.result.negativeInput), true);
  assert.equal(Number.isNaN(context.result.blankInput), true);
  assert.equal(context.result.fallbackValid, 42);
  assert.equal(context.result.fallbackInvalid, 7);
  assert.equal(context.result.displayZero, 0);
  assert.equal(context.result.displayInvalid, null);
}

function verifyMonitorConfigFormRejectsInvalidInputValues() {
  const mainSourcePath = path.resolve(__dirname, "..", "src", "main.js");
  const mainSource = fs.readFileSync(mainSourcePath, "utf8");
  const functionNames = [
    "normalizeText",
    "parseStrictInteger",
    "normalizePositiveInteger",
    "parseInputValue",
    "parseCompatibilityMode",
    "parseWindowsDisplayHandoffMode",
    "parseTargetId",
    "cloneInterfacesConfig",
    "createDefaultInterfacesConfig",
    "createDefaultMonitorConfig",
    "normalizeMonitorConfig",
    "getTargetSlotName",
    "getLocalInterfaceId",
    "getMonitorConfigValidationErrors",
    "buildMonitorConfigFromForm",
  ];
  const helperSource = functionNames.map((name) => extractFunction(mainSource, name)).join("\n");
  const script = `
    const TARGET_SLOTS = [
      { id: "dp1", title: "DP1", defaultInputValue: 15 },
      { id: "dp2", title: "DP2", defaultInputValue: 16 },
      { id: "hdmi1", title: "HDMI1", defaultInputValue: 17 },
      { id: "hdmi2", title: "HDMI2", defaultInputValue: 18 },
    ];
    const TARGET_SLOT_MAP = new Map(TARGET_SLOTS.map((slot) => [slot.id, slot]));
    const TARGET_IDS = TARGET_SLOTS.map((slot) => slot.id);
    ${helperSource}
    const existingMonitorConfig = {
      id: "monitor-test",
      displayKey: "mac-system:2",
      displayName: "H24E7",
      localInterfaceId: "hdmi1",
      peerInterfaceId: "dp2",
      compatibilityMode: "auto",
      windowsDisplayHandoffMode: "auto",
      interfaces: {
        dp1: { inputValue: 99, deviceLabel: "" },
        dp2: { inputValue: 16, deviceLabel: "" },
        hdmi1: { inputValue: 17, deviceLabel: "" },
        hdmi2: { inputValue: 18, deviceLabel: "" },
      },
      match: {},
    };
    const valid = buildMonitorConfigFromForm(new URLSearchParams(
      "localInterfaceId=hdmi1&peerInterfaceId=dp2&compatibilityMode=auto&windowsDisplayHandoffMode=auto&dp1InputValue=42&dp1DeviceLabel=&dp2InputValue=16&dp2DeviceLabel=&hdmi1InputValue=17&hdmi1DeviceLabel=&hdmi2InputValue=18&hdmi2DeviceLabel="
    ), existingMonitorConfig);
    const suffix = buildMonitorConfigFromForm(new URLSearchParams(
      "localInterfaceId=hdmi1&peerInterfaceId=dp2&compatibilityMode=auto&windowsDisplayHandoffMode=auto&dp1InputValue=17abc&dp1DeviceLabel=&dp2InputValue=16&dp2DeviceLabel=&hdmi1InputValue=17&hdmi1DeviceLabel=&hdmi2InputValue=18&hdmi2DeviceLabel="
    ), existingMonitorConfig);
    const outOfRange = buildMonitorConfigFromForm(new URLSearchParams(
      "localInterfaceId=hdmi1&peerInterfaceId=dp2&compatibilityMode=auto&windowsDisplayHandoffMode=auto&dp1InputValue=0&dp1DeviceLabel=&dp2InputValue=16&dp2DeviceLabel=&hdmi1InputValue=17&hdmi1DeviceLabel=&hdmi2InputValue=18&hdmi2DeviceLabel="
    ), existingMonitorConfig);
    globalThis.result = {
      validErrors: valid.errors,
      validDp1: valid.monitorConfig.interfaces.dp1.inputValue,
      suffixErrors: suffix.errors,
      outOfRangeErrors: outOfRange.errors,
    };
  `;
  const context = { URLSearchParams };
  vm.runInNewContext(script, context);
  assert.deepEqual(Array.from(context.result.validErrors), []);
  assert.equal(context.result.validDp1, 42);
  assert.deepEqual(Array.from(context.result.suffixErrors), ["DP1 的输入值必须是 1 到 255 的整数。"]);
  assert.deepEqual(Array.from(context.result.outOfRangeErrors), ["DP1 的输入值必须是 1 到 255 的整数。"]);
}

function verifyLocalOnlyDocs() {
  const readmePath = path.resolve(__dirname, "..", "README.md");
  const handoffDocPath = path.resolve(__dirname, "..", "docs", "shared-monitor-handoff.md");
  const readme = fs.readFileSync(readmePath, "utf8");
  const handoffDoc = fs.readFileSync(handoffDocPath, "utf8");

  assert.match(readme, /127\.0\.0\.1/u);
  assert.match(readme, /hardware identity/u);
  assert.match(readme, /日常使用逻辑/u);
  assert.match(readme, /交给对方机器/u);
  assert.match(readme, /日常交给对方接口/u);
  assert.match(readme, /连接设备名/u);
  assert.match(readme, /接回 Windows 的共享屏/u);
  assert.match(readme, /灰色第二屏/u);
  assert.match(handoffDoc, /no LAN peer discovery/u);
  assert.match(handoffDoc, /Daily user model/u);
  assert.match(handoffDoc, /A gray second screen in Windows Settings is not treated as proof/u);
  assert.match(handoffDoc, /Per-interface device labels are optional presentation labels only/u);
  assert.match(handoffDoc, /configured daily peer interface is the actual target/u);
  assert.match(handoffDoc, /does not blindly re-add a detached waiting screen/u);
  assert.match(handoffDoc, /takeover path first attaches the detached Windows display device/u);
  assert.match(handoffDoc, /hardware-bound/u);
  assert.match(handoffDoc, /same-model duplicate attached to Windows while its input is not that screen's configured local interface/u);
  assert.match(
    handoffDoc,
    /controls only the external physical screens that are currently attached to the local host/u
  );
  assert.doesNotMatch(handoffDoc, /includes a first peer-confirmation layer/u);
  assert.doesNotMatch(handoffDoc, /ownership endpoint on the LAN/u);
  assert.doesNotMatch(handoffDoc, /discovered Windows peer/u);
  assert.doesNotMatch(handoffDoc, /confirmed mismatch after readback is a real switch failure/u);
  assert.doesNotMatch(handoffDoc, /readback still stays on the old input, the failure means/u);
}

function verifyPinnedMacDdcctlBuildScript() {
  const buildScriptPath = path.resolve(__dirname, "..", "scripts", "build-macos-ddcctl.sh");
  const ensureScriptPath = path.resolve(__dirname, "..", "scripts", "ensure-macos-ddcctl.sh");
  const buildScript = fs.readFileSync(buildScriptPath, "utf8");
  const ensureScript = fs.readFileSync(ensureScriptPath, "utf8");
  const gitignore = fs.readFileSync(path.resolve(__dirname, "..", ".gitignore"), "utf8");

  assert.match(buildScript, /DDCCTL_COMMIT="([0-9a-f]{40})"/u);
  assert.match(buildScript, /git -C "\$WORK_DIR" fetch --depth 1 origin "\$DDCCTL_COMMIT"/u);
  assert.match(buildScript, /printf '%s\\n' "\$DDCCTL_COMMIT" > "\$OUTPUT_STAMP"/u);
  assert.match(ensureScript, /EXPECTED_COMMIT=\$\(awk -F'"'/u);
  assert.match(ensureScript, /rev-parse HEAD/u);
  assert.match(ensureScript, /"\$OUTPUT_STAMP"/u);
  assert.match(gitignore, /resources\/bin\/ddcctl\.commit/u);
}

function verifyWindowsHelperSourceGuards() {
  const topologyScript = fs.readFileSync(
    path.resolve(__dirname, "..", "resources", "windows", "display-topology.ps1"),
    "utf8"
  );
  const setInputScript = fs.readFileSync(
    path.resolve(__dirname, "..", "resources", "windows", "set-input.ps1"),
    "utf8"
  );

  assert.match(topologyScript, /PromotePrimaryAwayFromDisplay/u);
  assert.match(topologyScript, /ApplyPrimaryDisplayWithStableLayout/u);
  assert.match(topologyScript, /display\.PositionX - offsetX/u);
  assert.match(topologyScript, /display\.PositionY - offsetY/u);
  assert.match(topologyScript, /preferredModeDisplayEntry/u);
  assert.match(topologyScript, /resolvedPreferredWidth/u);
  assert.match(topologyScript, /RollbackDisplayModes/u);
  assert.match(setInputScript, /\[switch\]\$ProbeDdc/u);
  assert.match(setInputScript, /physicalMonitorCount/u);
  assert.match(setInputScript, /probeScope = "physicalMonitorHandle"/u);
  assert.doesNotMatch(setInputScript, /capabilitiesAvailable/u);
}

function verifyCiWorkflowTriggers() {
  const workflowPath = path.resolve(__dirname, "..", ".github", "workflows", "release.yml");
  const workflow = fs.readFileSync(workflowPath, "utf8");

  assert.match(workflow, /pull_request:/u);
  assert.match(workflow, /branches:\s*\n\s*- main/u);
  assert.match(workflow, /tags:\s*\n\s*- "v\*"/u);
  assert.match(workflow, /permissions:\s*\n\s*contents: read/u);
  assert.match(workflow, /create-release:/u);
  assert.match(workflow, /release-windows:/u);
  assert.match(workflow, /release-macos:/u);
  assert.match(workflow, /contents: write/u);
  assert.match(workflow, /gh release upload/u);
  assert.match(workflow, /npm run dist:win/u);
  assert.match(workflow, /npm run dist:mac/u);
  assert.doesNotMatch(workflow, /npm run release/u);
}

function findPowerShellCommand() {
  for (const command of ["pwsh", "powershell.exe"]) {
    try {
      execFileSync(command, ["-NoProfile", "-Command", "$PSVersionTable.PSVersion.ToString()"], {
        stdio: "pipe",
        encoding: "utf8",
      });
      return command;
    } catch {
      // Try the next PowerShell executable.
    }
  }

  return null;
}

function verifyWindowsScriptSyntax(powerShellCommand) {
  const topologyScriptPath = path.resolve(
    __dirname,
    "..",
    "resources",
    "windows",
    "display-topology.ps1"
  );
  const setInputScriptPath = path.resolve(
    __dirname,
    "..",
    "resources",
    "windows",
    "set-input.ps1"
  );
  const syntaxCheckCommand = `
$ErrorActionPreference = 'Stop'
$scripts = @(
  '${topologyScriptPath.replace(/'/gu, "''")}',
  '${setInputScriptPath.replace(/'/gu, "''")}'
)
foreach ($script in $scripts) {
  $tokens = $null
  $errors = $null
  [System.Management.Automation.Language.Parser]::ParseFile($script, [ref]$tokens, [ref]$errors) | Out-Null
  if ($errors.Count -gt 0) {
    throw ($errors | ForEach-Object { $_.Message } | Out-String)
  }
}
`;

  execFileSync(powerShellCommand, ["-NoProfile", "-Command", syntaxCheckCommand], {
    stdio: "pipe",
    encoding: "utf8",
  });
}

function readPlistJson(plistPath) {
  return JSON.parse(run("/usr/bin/plutil", ["-convert", "json", "-o", "-", plistPath]));
}

function isMacPathHidden(appPath) {
  try {
    if (run("/usr/bin/mdls", ["-name", "kMDItemFSInvisible", "-raw", appPath]) === "1") {
      return true;
    }
  } catch {
    // Fall through to filesystem flags below.
  }

  try {
    return run("/usr/bin/stat", ["-f", "%Sf", appPath]).split(",").includes("hidden");
  } catch {
    return false;
  }
}

function verifyMacHelperApps(appBundlePath) {
  if (!fs.existsSync(appBundlePath)) {
    throw new Error(`App bundle not found: ${appBundlePath}`);
  }

  const frameworksDir = path.join(appBundlePath, "Contents", "Frameworks");
  const helperApps = fs
    .readdirSync(frameworksDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && entry.name.endsWith(".app"))
    .map((entry) => entry.name)
    .sort();

  assert.deepEqual(helperApps, [
    "显示器输入切换 Helper (GPU).app",
    "显示器输入切换 Helper (Plugin).app",
    "显示器输入切换 Helper (Renderer).app",
    "显示器输入切换 Helper.app",
  ]);

  for (const helperName of helperApps) {
    const helperPath = path.join(frameworksDir, helperName);
    const plistPath = path.join(helperPath, "Contents", "Info.plist");
    const iconPath = path.join(helperPath, "Contents", "Resources", "icon.icns");
    const plist = readPlistJson(plistPath);

    assert.equal(plist.CFBundleIconFile, "icon.icns");
    assert.equal(fs.existsSync(iconPath), true, `${iconPath} should exist`);
    assert.equal(isMacPathHidden(helperPath), true);
    assert.match(plist.CFBundleName, /^显示器输入切换 Helper/u);
  }

  const bundledDdcctlPath = path.join(
    appBundlePath,
    "Contents",
    "Resources",
    "resources",
    "bin",
    "ddcctl"
  );
  assert.equal(
    fs.existsSync(bundledDdcctlPath),
    true,
    `${bundledDdcctlPath} should exist`
  );

  const bundledWindowsTopologyHelperPath = path.join(
    appBundlePath,
    "Contents",
    "Resources",
    "resources",
    "windows",
    "display-topology.ps1"
  );
  assert.equal(
    fs.existsSync(bundledWindowsTopologyHelperPath),
    true,
    `${bundledWindowsTopologyHelperPath} should exist`
  );
}

function writeFakeDdcctlBinary(fakeBinaryPath, mode) {
  const script = `#!/bin/sh
set -eu
if [ "\${1:-}" = "-h" ]; then
  if [ "${mode}" = "missing-count" ]; then
    cat <<'EOF'
Usage:
ddcctl    -d <1-..> [display#]
EOF
  else
    cat <<'EOF'
Usage:
ddcctl    -d <1-..> [display#]
I: found 1 external display
EOF
  fi
  exit 0
fi

if [ "\${1:-}" = "-d" ] && [ "\${2:-}" = "1" ] && [ "\${3:-}" = "-i" ] && [ "\${4:-}" = "16" ]; then
  echo "OK"
  exit 0
fi

if [ "\${1:-}" = "-d" ] && [ "\${2:-}" = "1" ] && [ "\${3:-}" = "-i" ] && [ "\${4:-}" = "?" ]; then
  if [ "${mode}" = "matched" ]; then
    echo "VCP 0x60 current: 16 max: 18"
  elif [ "${mode}" = "query-fails" ]; then
    echo "readback unavailable" >&2
    exit 1
  else
    echo "VCP 0x60 current: 6 max: 18"
  fi
  exit 0
fi

echo "unexpected args: $*" >&2
exit 1
`;

  fs.writeFileSync(fakeBinaryPath, script, { mode: 0o755 });
}

function verifyMacDdcctlFallbackScript() {
  const switchScriptPath = path.resolve(
    __dirname,
    "..",
    "resources",
    "mac",
    "switch-input.sh"
  );
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "monitor-input-switch-selftest-"));
  const fakeBinaryPath = path.join(tempDir, "fake-ddcctl");
  const baseEnv = {
    ...process.env,
    DISPLAY_NAME: "Local Monitor",
    DISPLAY_INDEX: "1",
    DISABLE_BETTERDISPLAY: "1",
    BUNDLED_DDCCTL_PATH: fakeBinaryPath,
    PATH: "/usr/bin:/bin:/usr/sbin:/sbin",
  };

  writeFakeDdcctlBinary(fakeBinaryPath, "matched");
  execFileSync("/bin/sh", [switchScriptPath, "16"], {
    env: baseEnv,
    stdio: "pipe",
    encoding: "utf8",
  });

  writeFakeDdcctlBinary(fakeBinaryPath, "unchanged");
  const mismatchOutput = execFileSync("/bin/sh", [switchScriptPath, "16"], {
    env: baseEnv,
    stdio: "pipe",
    encoding: "utf8",
  });
  assert.match(mismatchOutput, /UNCONFIRMED/u);

  const probeOutput = execFileSync("/bin/sh", [switchScriptPath, "--probe-ddc"], {
    env: baseEnv,
    stdio: "pipe",
    encoding: "utf8",
  }).trim();
  assert.equal(probeOutput, "OK");

  writeFakeDdcctlBinary(fakeBinaryPath, "query-fails");
  const unconfirmedOutput = execFileSync("/bin/sh", [switchScriptPath, "16"], {
    env: baseEnv,
    stdio: "pipe",
    encoding: "utf8",
  });
  assert.match(unconfirmedOutput, /UNCONFIRMED/u);

  writeFakeDdcctlBinary(fakeBinaryPath, "missing-count");
  let queryFailure = null;
  try {
    execFileSync("/bin/sh", [switchScriptPath, "--query-input"], {
      env: baseEnv,
      stdio: "pipe",
      encoding: "utf8",
    });
  } catch (error) {
    queryFailure = error;
  }

  assert.ok(queryFailure, "ddcctl query fallback should fail closed when display count is unknown");
  assert.match(
    `${queryFailure.stderr || queryFailure.message}`,
    /ddcctl 没有可靠返回外接屏数量/u
  );

  let missingCountFailure = null;
  try {
    execFileSync("/bin/sh", [switchScriptPath, "16"], {
      env: baseEnv,
      stdio: "pipe",
      encoding: "utf8",
    });
  } catch (error) {
    missingCountFailure = error;
  }

  assert.ok(missingCountFailure, "ddcctl switch fallback should fail closed when display count is unknown");
  assert.match(
    `${missingCountFailure.stderr || missingCountFailure.message}`,
    /ddcctl 没有可靠返回外接屏数量/u
  );
}

function writeFakeBetterDisplayBinary(fakeBinaryPath, mode = "normal") {
  const script = `#!/bin/sh
set -eu

joined="$*"

case "$joined" in
  get*" -displayID=777 "*|get*" -displayID=777")
    echo "display id not found" >&2
    exit 1
    ;;
  set*" -displayID=777 "*|set*" -displayID=777")
    echo "display id not found" >&2
    exit 1
    ;;
  set*" -nameLike=Fallback Monitor "*" -vcp=inputSelect "*|set*" -nameLike=Fallback Monitor"*" -vcp=inputSelect")
    echo "OK"
    exit 0
    ;;
  get*" -nameLike=Fallback Monitor "*" -vcp=inputSelect "*|get*" -nameLike=Fallback Monitor"*" -vcp=inputSelect")
    if [ "${mode}" = "write-only" ]; then
      echo "readback unavailable" >&2
      exit 1
    fi
    echo "16"
    exit 0
    ;;
  set*" -nameLike=Fallback Monitor "*" -vcp=0x60 "*|set*" -nameLike=Fallback Monitor"*" -vcp=0x60")
    echo "OK"
    exit 0
    ;;
  get*" -nameLike=Fallback Monitor "*" -vcp=0x60 "*|get*" -nameLike=Fallback Monitor"*" -vcp=0x60")
    if [ "${mode}" = "write-only" ]; then
      echo "readback unavailable" >&2
      exit 1
    fi
    echo "16"
    exit 0
    ;;
esac

echo "unexpected args: $*" >&2
exit 1
`;

  fs.writeFileSync(fakeBinaryPath, script, { mode: 0o755 });
}

function verifyMacBetterDisplayFallbackScript() {
  const switchScriptPath = path.resolve(
    __dirname,
    "..",
    "resources",
    "mac",
    "switch-input.sh"
  );
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "monitor-input-switch-bd-selftest-"));
  const fakeBinaryPath = path.join(tempDir, "fake-betterdisplay");
  const baseEnv = {
    ...process.env,
    DISPLAY_NAME: "Fallback Monitor",
    DISPLAY_ID: "777",
    DISPLAY_NAME_FALLBACK_ALLOWED: "1",
    BETTERDISPLAY_APP_PATH: fakeBinaryPath,
    BUNDLED_DDCCTL_PATH: path.join(tempDir, "missing-ddcctl"),
    PATH: "/usr/bin:/bin:/usr/sbin:/sbin",
  };

  writeFakeBetterDisplayBinary(fakeBinaryPath);

  execFileSync("/bin/sh", [switchScriptPath, "16"], {
    env: baseEnv,
    stdio: "pipe",
    encoding: "utf8",
  });

  const queryOutput = execFileSync("/bin/sh", [switchScriptPath, "--query-input"], {
    env: baseEnv,
    stdio: "pipe",
    encoding: "utf8",
  }).trim();

  assert.equal(queryOutput, "16");
}

function verifyMacBetterDisplayWriteOnlyProbeScript() {
  const switchScriptPath = path.resolve(
    __dirname,
    "..",
    "resources",
    "mac",
    "switch-input.sh"
  );
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "monitor-input-switch-bd-writeonly-selftest-"));
  const fakeBinaryPath = path.join(tempDir, "fake-betterdisplay");
  const baseEnv = {
    ...process.env,
    DISPLAY_NAME: "Fallback Monitor",
    DISPLAY_ID: "777",
    DISPLAY_NAME_FALLBACK_ALLOWED: "1",
    BETTERDISPLAY_APP_PATH: fakeBinaryPath,
    BUNDLED_DDCCTL_PATH: path.join(tempDir, "missing-ddcctl"),
    PATH: "/usr/bin:/bin:/usr/sbin:/sbin",
  };

  writeFakeBetterDisplayBinary(fakeBinaryPath, "write-only");

  const probeOutput = execFileSync("/bin/sh", [switchScriptPath, "--probe-ddc"], {
    env: baseEnv,
    stdio: "pipe",
    encoding: "utf8",
  }).trim();
  assert.equal(probeOutput, "UNKNOWN");

  const switchOutput = execFileSync("/bin/sh", [switchScriptPath, "16"], {
    env: baseEnv,
    stdio: "pipe",
    encoding: "utf8",
  });
  assert.match(switchOutput, /UNCONFIRMED/u);
}

function verifyMacHelperAppsIfAvailable() {
  if (process.env.SELF_VERIFY_REQUIRE_MAC_APP_BUNDLE !== "1") {
    return;
  }

  const builtAppPath = path.resolve(
    __dirname,
    "..",
    "release",
    "mac-arm64",
    "显示器输入切换.app"
  );
  if (fs.existsSync(builtAppPath)) {
    verifyMacHelperApps(builtAppPath);
    return;
  }

  if (process.env.SELF_VERIFY_ALLOW_INSTALLED_MAC_APP_BUNDLE !== "1") {
    throw new Error(`No built macOS app bundle was found: ${builtAppPath}`);
  }

  const installedAppPath = "/Applications/显示器输入切换.app";
  if (fs.existsSync(installedAppPath)) {
    verifyMacHelperApps(installedAppPath);
    return;
  }

  throw new Error("No macOS app bundle was found for self verification.");
}

function main() {
  verifyMainSourceSyntax();
  verifyMainSourceBusinessGuards();
  verifyMacMonitorConfigSyncBehavior();
  verifyStrictIntegerParsing();
  verifyMonitorConfigFormRejectsInvalidInputValues();
  verifyLocalOnlyDocs();
  verifyPinnedMacDdcctlBuildScript();
  verifyWindowsHelperSourceGuards();
  verifyCiWorkflowTriggers();

  const powerShellCommand = findPowerShellCommand();
  if (powerShellCommand) {
    verifyWindowsScriptSyntax(powerShellCommand);
  }

  if (process.platform === "darwin") {
    verifyMacDdcctlFallbackScript();
    verifyMacBetterDisplayFallbackScript();
    verifyMacBetterDisplayWriteOnlyProbeScript();
    verifyMacHelperAppsIfAvailable();
  }

  process.stdout.write("Self verification passed.\n");
}

main();
